### ISSUE TITLE
[FEATURE REQ] Decouple knowledge gpg tooling location.

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-java#10196]
Decouple knowledge of where the gpg tooling lives between different steps in archetype-java-release.yml.

```
- template: tools/gpg/gpg.yml@azure-sdk-build-tools
  parameters: 
    GPGPath: $(GPGPath) # We could consider either passing it to both or making GPGPath an output variable from this template. 

- template: /eng/pipelines/templates/steps/java-publishing.yml
  parameters:
    ArtifactID: ${{artifact.name}}
    GroupID: ${{artifact.groupId}}
    ArtifactDirectory: $(Pipeline.Workspace)/${{parameters.ArtifactName}}-signed
    Target: MavenCentral
    GPGPath: $(GPGPath)
```
