### ISSUE TITLE
allowed-groups doesn't work as a collection

### ISSUE THREAD

**Issue by jvalkeal** [Azure/azure-sdk-for-java#14604]
When `azure.activedirectory.user-group.allowed-groups` is defined as a collection, `AADOAuth2UserService` doesn't get created.

https://github.com/Azure/azure-sdk-for-java/blob/5843d992409a7db0a26b73caba93d1d7bdd52d23/sdk/spring/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/aad/AADOAuth2AutoConfiguration.java#L55

It works with:
```
azure:
  activedirectory:
    user-group:
      allowed-groups: group1,group2
```

but not with:
```
azure:
  activedirectory:
    user-group:
      allowed-groups:
        - group1
        - group2
```
This is described in a javadocs for `@ConditionalOnProperty` briefly discussed in spring-projects/spring-boot#7483

I'd recommend to find a better conditional to properly check if user defined a property regardless on what format was used.
