### ISSUE TITLE
Too many redirects after login

### ISSUE THREAD

**Issue by drhae** [Azure/azure-sdk-for-java#19131]
Hello. I am trying to get this sample to run as a war file on a server instead of as a jar. When I deploy it though, it will prompt for the b2c login, then get caught in a redirect loop until it fails. 

To change it to deploy as war file i did these steps:
1    changed packaging in pom to war
 2   added exclusion under spring boot starter web
 ```
  <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
         <exclusions>
          <exclusion>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <groupId>org.springframework.boot</groupId>
          </exclusion>
        </exclusions>
    </dependency>
```
3    added dependancy for javax serlvet
  ```
 <dependency>
          <groupId>javax.servlet</groupId>
          <artifactId>jsp-api</artifactId>
          <version>2.0</version>
          <scope>provided</scope>
    </dependency>
```

4    Changed the application class to extend SpringBootServletInitializer
```
@SpringBootApplication
public class AzureADB2COIDCSampleApplication extends SpringBootServletInitializer {
    public static void main(String[] args) {       
        SpringApplication.run(AzureADB2COIDCSampleApplication.class, args);
    }
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(AzureADB2COIDCSampleApplication.class);
    }
}

```
Any ideas why this would fail when deployed that way but work fine when running through ide as jar file?

**Comment by joshfree** [comment]
@jialindai could you please assist?

**Comment by backwind1233** [comment]
Hi, @drhae 
I tried to reproduce the problem you have met, but it seems to work for me.

The only difference when I deploy the sample as war is that I added a maven
 dependency

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
      <scope>provided</scope>
    </dependency>
``` 
the sample code I used is of the[ current master branch ](https://github.com/Azure/azure-sdk-for-java/tree/5a1ebdfedd15d2967725098827cbe2451db38b82/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc)

![image](https://user-images.githubusercontent.com/4465723/108465478-0e588600-72bd-11eb-9c7d-424911f186ce.png)

My yaml config is like this:
```
azure:
  activedirectory:
    b2c:
      base-uri: ${your-tenant-authorization-server-base-uri}
      client-id: ${your-client-id}
      client-secret: ${your-client-secret}
      logout-success-url: ${your-logout-success-url}
      user-name-attribute-name: ${your-user-name-claim}
      user-flows:
        sign-up-or-sign-in: ${your-sign-up-or-in-user-flow}
        profile-edit: ${your-profile-edit-user-flow}     # optional
        password-reset: ${your-password-reset-user-flow} # optional
```

Could you please try it again?
Please give more information (eg: commit id) if you still fail to deploy the war.
