### ISSUE TITLE
azure.activedirectory.redirect-uri-template not work

### ISSUE THREAD

**Issue by gitercn** [Azure/azure-sdk-for-java#19680]
**Query/Question**
A clear and concise ask/query.

Currently my app's redirect url is set to "https://app1-test.xxx.com/oauth/redirect". However, when I follow this tutorial https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter_3.1.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp , the default redirect url is set to "https://app1-test.xxx.com/login/oauth2/code/azure". Then when I run it, it get the error "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application".

My app is managed by my organization's manager I can't change the redirect url by myself (it's grayed out in the portal.azure.com). So I tried to set redirect url in the application.yml. I set the azure.activedirectory.redirect-uri-template in the file, but it seems it does not work. The redirect url is still the wrong one.

My application.yml now looks like this:

```
azure:
  activedirectory:
    redirect-uri-template: https://app1-test.xxx.com/oauth/redirect
    authorization-clients:
      arm:
        on-demand: true
        scopes: https://management.core.windows.net/user_impersonation
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
          - https://graph.microsoft.com/Directory.Read.All
    client-id: xxx
    client-secret: xxx
    tenant-id: xxx
    user-group:
      allowed-groups: group1, group2
    post-logout-redirect-uri: https://app1-test.xxx.com/oauth/redirect

server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
```

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

I don't know whether the azure.activedirectory.redirect-uri-template is for something else or it's not working due to a bug.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Windows 10
 - IDE : [e.g. IntelliJ] Eclipse
 - Version of the Library used 3.1.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added
