### ISSUE TITLE
[QUERY]How to remove unnecessary permissions.

### ISSUE THREAD

**Issue by rami2076** [Azure/azure-sdk-for-java#19712]
**Query/Question**
How to remove unnecessary permissions.

Is it possible to exclude it in the Spring settings?
I'm currently trying to use the following settings to set the scope to "openid" only, but it's sending different requests than expected.

Sending scope is openid ,profile , https://graph.microsoft.com/User.Read ,https://graph.microsoft.com/Directory.AccessAsUser.All .

Current settings (application.yml)
```
azure:
  activedirectory:
    tenant-id: {tenant-id}
    client-id: {client-id} 
    client-secret: {client-secret}
    user-group:
      allowed-groups: {allowed-group}
    authorization-clients:
      graph:
        scopes: openid ##<-Set scope.
```

actual request:
```
https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/authorize?response_type=code&client_id={client-id} &scope=openid%20profile%20offline_access%20https://graph.microsoft.com/User.Read%20https://graph.microsoft.com/Directory.AccessAsUser.All&state=xScZnycXNh2GOWMdgeMX_FP6OC-fXm07-RaakvlDbIo%3D&redirect_uri={baseuri}/login/oauth2/code/azure&nonce={nonce}
```

**Setup :**
 - azure-spring-boot-starter-active-directory version 3.1.0
 -
