### ISSUE TITLE
[FEATURE REQ] Add more configuration items for resource-server

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#21005]
Required by @einue

Add more configuration items for resource-server. Like this:
```
azure:
  activedirectory:
    resource-server:
      authorities-claim-name: group
      authority-prefix: ROLE_
      principal-claim-name: sub
```

Related issue: https://github.com/Azure/azure-sdk-for-java/issues/20980#issuecomment-828070067
