### ISSUE TITLE
Realize azure credential chain to simplify and unify developer credential management experience across spring libraries.

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21472]
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-identity-spring

To provide a unified way for Spring users to provide their credentials to authenticate with AAD. Each starter should share the same configuration fields, which will be used to auto-wire a credential, while each service could specify a service dedicated credential:
```yaml
spring.cloud.azure:
  credential:
    client-id:
    client-secret:
    client-certificate-path:
    authority-host:
  servicebus:
    credential:
      client-id:
      client-secret:
      client-certificate-path:
      authority-host:

```
However, each service has authentication methods that only apply to themselves, check this wiki https://github.com/Azure/azure-sdk-for-java/wiki/Spring:-Unify-Azure-Credentials-construction-in-Azure-Spring.
