### ISSUE TITLE
Enable way for pipelines to specify additional options to maven without overriding everything.

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#21903]
For example:

```
TestStepMavenInputs: 
   goals: verify
   options: '$(DefaultTestOptions) $(ProfileFlag) $(AdditionalArgs)'
   mavenOptions: '$(DefaultTestMavenOptions)'
```
In order to simply pass one additional command line option you have to pass all inputs via TestStepMavenInputs. This causes lots of room for mistakes and duplication. Instead we should add some parameter or variable that people can set that will just append the options to the default command lines. 

See https://github.com/Azure/azure-sdk-for-java/pull/21797#discussion_r640784365 for some discussion in a recent PR.
