### ISSUE TITLE
Deprecate `aad.group.enable-full-list`, use `aad.group.allowed-group-ids=*` instead

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#21983]
the aad group configuration 
```
aad:
   group:
     allowed-group-names: group-name-1, group-name-2
     allowed-group-ids: id1
     enable-full-list: false    
```
the name of  `enable-full-list` may be confused for users, since if the value is `true`, it will ingnore `allowed-group-names`.

---
Here is new design:

1. Deprecate `enable-full-list`.
2. Use `allowed-group-ids = all` to implement function of `enable-full-list`.
3. Let `allowed-group-ids = all` can work together with `allowed-group-names`.
---

https://github.com/Azure/azure-sdk-for-java/issues/20218#issuecomment-827476074
