### ISSUE TITLE
[QUERY] Support needed setting up client credential flow with Spring Boot app

### ISSUE THREAD

**Issue by BillyBolton** [Azure/azure-sdk-for-java#22642]
**Query/Question**
Question also posted on StackOverflow [here](https://stackoverflow.com/questions/68181260/setup-azure-client-credential-flow-with-spring).

I'm trying to setup client credential flow with a Spring app to access a web api (both owned by myself). I've attempted to follow the Azure documentation [Microsoft identity platform and the OAuth 2.0 client credentials flow][1] and [Quickstart: Configure a client application to access a web API][2] but I'm running into a few problems because the documentation is not clear. Somewhere in my setup, Azure is forcing the user to sign-in, and then other error messages sprout from there. As we know, however, client credential should be machine to machine authorization so I'm not sure why this sign-in flow is happening.

Below are some photos of my setup from Azure and the applications.yml file. Any feedback would be helpful getting me up running.

 **application.yml**

```
 azure:
  activedirectory:
    tenant-id: {my-web-app-tenant-id}
    client-id: {my-web-app-client-id}
    client-secret: {my-web-app-client-secret}
    authorization-clients:
     web-api:
       scopes:
         - api://example-api/Employees.Read.All
         - api://example-api/Employees.Write.All
```
[![Web-app and web-api registered applications][3]][3]

[![Web-api scopes and authorized client which matches web-app client][4]][4]

[![Web-app authentication setup][5]][5]

[![Web-App permissions, including permission for web-api][6]][6]

  [1]: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow
  [2]: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis
  [3]: https://i.stack.imgur.com/pYTSC.jpg
  [4]: https://i.stack.imgur.com/NWsXz.jpg
  [5]: https://i.stack.imgur.com/yJb8z.jpg
  [6]: https://i.stack.imgur.com/GIgmN.jpg

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 20.10
 - IDE: Visual Studio Code
 - Library/Libraries: 
 - com.azure.spring:azure-spring-boot-starter-active-directory:3.5.0
 - org.springframework.boot:spring-boot-starter-oauth2-client
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @BillyBolton, someone from the `azure-spring` team will follow up with you shortly.

/cc @stliu

**Comment by BillyBolton** [comment]
Update:
From the steps [here](https://stackoverflow.com/questions/68181260/setup-azure-client-credential-flow-with-spring), I was able to get the token I wanted using Postman. The missing step was to make an App Role from the api, and then use application permissions for that role on the client side.

Unfortunately, I'm still getting the same sign-in flow though, which makes me think there's an issue on the Spring boot configuration. Would you be able to clarify what the applications.yml file needs to look like for this flow? (I've been looking at the documentation and it's really not clear).
```
 azure:
  activedirectory:
    tenant-id: {my-web-app-tenant-id}
    client-id: {my-web-app-client-id}
    client-secret: {my-web-app-client-secret}
    authorization-clients:
     web-api:
       scopes:
         - api://example-api/.default
```

**Comment by chenrujun** [comment]
Hi, @BillyBolton .

Thanks for reaching out.
Sorry for late response.

Could you please try this:
```
 azure:
  activedirectory:
    tenant-id: {my-web-app-tenant-id}
    client-id: {my-web-app-client-id}
    client-secret: {my-web-app-client-secret}
    authorization-clients:
     web-api:
       scopes:
         - api://example-api/.default
       authorization-grant-type: client_credentials   # Add this line.
```

And I'll create a PR soon about the docs and sample project.
