### ISSUE TITLE
Why do you use key instead of value for user-flows?

### ISSUE THREAD

**Issue by kesuke-t** [Azure/azure-sdk-for-java#24256]
https://github.com/Azure/azure-sdk-for-java/blob/945e3147608ebffbe1ffa392be21f26d73aea90d/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CTrustedIssuerRepository.java#L45

In the following B2C configuration, instead of using the value value of sign-up-or-sign-in
key value, we have to define a dummy key-value.

```
azure:
  activedirectory:
    b2c:
      ...
      user-flows:
        sign-up-or-sign-in: B2C_xxx_yyy
        B2C_xxx_yyy: B2C_xxx_yyy_dummy
      ...
```
