### ISSUE TITLE
[FEATURE REQ] Support all configurations for the initial position for an Event Hub partitition

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26434]
**Is your feature request related to a problem? Please describe.**
In the 4.0.0-beta.2 only `earliest` and `latest` positions are supported for configuring the consuming initial position, but the `EventPostition` in EventProcessorClient supports passing offset, sequence number, and enquedDatetime. We should support all of them like this:

```yaml
spring:
  cloud:
    stream:
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              initial-partition-event-position:
                0:
                  offset: earliest
                1:
                  sequence-number: 100
                2:
                  enqueued-date-time: 2022-01-12T13:32:47.650005Z
                3: 
                  offset: 19400
```

**Describe the solution you'd like**
Support all configuration options for the starting position.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified
