### ISSUE TITLE
[FEATURE REQ]servicebus jms connection-string enhance

### ISSUE THREAD

**Issue by jialigit** [Azure/azure-sdk-for-java#26551]
**Is your feature request related to a problem? Please describe.**
For now, serivcebus jms starter's credential can only be configured using the configuration option of "spring.jms.servicebus.connection-string". We also need to support the option of :
1.   configuration option of "spring.cloud.azure.servicebus.connection-string". 
2.  configuration of  "spring.cloud.azure.servicebus.namespace" used with "credential" option, i.e.  
the following configuration can be used.
```
#
spring:
  jms:
    servicebus:
      connection-string:  ${AZURE_SERVICEBUS_CONNECTION_STRING}
```
and 
```application-sp.yml
spring:
  cloud:
    azure:
      servicebus:
        connection-string:  ${AZURE_SERVICEBUS_CONNECTION_STRING}
 ...
```

OR

```
spring:
  cloud:
    azure:
      credential:
        client-id:  ${AZURE_CLIENT_ID}
        client-secret:  ${AZURE_CLIENT_SECRET}
      profile:
          tenant-id:  ${AZURE_TENANT_ID}
          subscription-id:  ${SUBSCRIPTION_ID}
      servicebus:
        resource:
          resource-group:  ${RESOURCE_GROUP}
        namespace: ${NAMESPACE}


```
**Describe the solution you'd like**
1. Add dependency of 
```
<dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>spring-cloud-azure-resourcemanager</artifactId>
      <version>4.0.0-beta.3</version> <!-- {x-version-update;com.azure.spring:spring-cloud-azure-resourcemanager;current} -->
    </dependency>
```

in the servicebus-jms-starter artifact pom.
which will enable the auto-configuration of azure-resource-manager.
2. Declare a StaticConnectionProvider bean for ServiceBus and the AzureServiceBusJmsProperties bean.
**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified
