### ISSUE TITLE
[Bug] Spring Cloud Azure Storage file doesn't support path contains directory.

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26659]
**Context**
When using Spring Resource and Spring Cloud Azure Storage file to read and write files, if the resource location configured with pattern `azure-file:fileshare/foldera/folderb/folderc/a.txt`

**Steps to reproduce issue**
Use the [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/storage/spring-cloud-azure-starter-storage-file-share/storage-file-sample) to demonstrate this issue: 
Configure the `application.yml`

```
spring:
  cloud:
    azure:
      storage:
        fileshare:
          account-name: [storage-account-name]
          account-key: [storage-account-access-key]
          endpoint:  [Fill storage File service endpoint URL copied from portal]
# Resource location, used in this sample
resource:
  file: [azure-file://[your-fileshareName]/[your-fileName]]
```
1. Configure `resource:file` with patterns: `azure-file:${yourfileshare}/a.txt` , it will work.
2. Configure `resource:file` with patterns: `azure-file:${yourfileshare}/foldera/folderb/folderc/a.txt`, it will fail.

**Expected behavior**
It's expect to create  folders automatically  when configure `resource:file` with patterns: `azure-file:${yourfileshare}/foldera/folderb/folderc/a.txt`.
