### ISSUE TITLE
[QUERY] Breaking change introduced in azure-spring-cloud-appconfiguration-config minor version upgrade

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/azure-sdk-for-java#26777]
Have we introduced a breaking change in **`bootstrap.yml`** configuration while upgrading the minor version from **`2.0.0`** to **`2.1.0`** for **`azure-spring-cloud-appconfiguration-config`**? 

**Configuration that works in version `2.0.0`**
```
spring:
  cloud:
    azure:
      appconfiguration:
        stores:
          - store:
            endpoint: ${APP_CONFIG_ENDPOINT}
            label: ${APP_CONFIG_LABEL}
        defaultContext: ${APP_CONFIG_DEFAULT_NAMESPACE}
        name: ${APP_CONFIG_APPLICATION_NAMESPACE}
```

**Configuration that works in version `2.1.0`**
```
spring:
  cloud:
    azure:
      appconfiguration:
        stores:
          - store:
            endpoint: ${APP_CONFIG_ENDPOINT}
            selects:
              - select:
                keyFilter: /${APP_CONFIG_DEFAULT_NAMESPACE}/
                labelFilter: ${APP_CONFIG_LABEL}
              - select:
                keyFilter: /${APP_CONFIG_APPLICATION_NAMESPACE}/
                labelFilter: ${APP_CONFIG_LABEL}
```

The configuration that works in version `2.0.0` does not work in version `2.1.0`. This breaking change does not seem to be documented in release notes and was unexpected in a minor version upgrade.

Also, can you pls confirm what convention for `bootstrap.yml` configuration will be followed going forward in future minor version upgrades so that such undocumented breaking changes does not take the users by surprise.
