### ISSUE TITLE
Add Cosmos sample for using Client Secret Credentials  

### ISSUE THREAD

**Issue by coder-hop** [Azure/azure-sdk-for-java#26865]
**Is your feature request related to a problem? Please describe.**
Service Principle is used in most production application where cosmos is used , the sample code(azure-sdk-for-java/sdk/cosmos/azure-spring-data-cosmos/src/samples/) only have configuration snippet related to key-based credentials, Client Secret Credentials configuration also need to be added to help users.

**Describe the solution you'd like**
Add the snippet for passing ClientSecretCredential to CosmosClientBuilder  

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [X ] Expected solution specified

**Comment by joshfree** [comment]
@saragluna could you please follow up with @coder-hop

**Comment by saragluna** [comment]
Hi @coder-hop, thanks for the feedback. 

We have fixed the auto-configuration of Spring Data Cosmos in our next major version (which is not GAed yet), you could take a look at this sample, https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/cosmos/spring-cloud-azure-starter-data-cosmos/spring-cloud-azure-data-cosmos-sample. 

To use a ClientSecretCredential, you can specify the below properties:
```yaml
spring:
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        database: ${COSMOS_DATABASE}
        credential:
          client-id: your-service-principal-id
          client-secret: your-service-principal-secret
```

But since the 4.0 version has many breaking changes in artifact id and configuration properties, you could follow this doc https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.3/4.0.0-beta.3/reference/html/appendix.html#migration-guide-for-4-0 for migration.
