### ISSUE TITLE
Re-design the configuration properties about key vault secrets.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27392]
Continue to #27256, we need re-design the configuration properties about key vault secrets.

Here is an proposal:
```
spring:
  cloud:
    azure:
      keyvault:
        secret:
          enabled:
          endpoint:
          property-source:
            enabled: ## switch for all property sources.
            property-sources: ## This is a map, like Map<String, KeyVaultPropertySourceProperty>
              property-source-0: ## This is property source name.
                enabled: ## switch for this property source.
                endpoint:
                # Some other properties in AzureKeyVaultPropertySourceProperties
              property-source-1:
                enabled:
                endpoint:
                # Some other properties in AzureKeyVaultPropertySourceProperties
              ... # Other property sources.
```

This is not the final design, we need more considerations about each property item.

**Comment by chenrujun** [comment]
Here is another proposal:
```
spring:
  cloud:
    azure:
      keyvault:
        secret:
          enabled: # It can disable the autoconfigured bean, but can not disable property-source.
          endpoint: # Azure Key Vault endpoint.
        secret-property-source:
          enabled: # It can disable all property source.
          property-sources: ## This is a List, like List<KeyVaultPropertySourceProperty>, and the order matters
            - name: # property source name.
              enabled: # It can disable this property source
              endpoint: # Azure Key Vault endpoint.
              service-version: # Map to SecretClientBuilder#serviceVersion
              case-sensitive: # Whether secret key name is case-sensitive.
              secret-keys: key1, key2 # secret keys supported for this property source
              refresh-interval: 30s
              credential: # Properties used for getting token credential.
                client-id: # Client id to use when performing service principal authentication with Azure.
                client-secret: # Client secret to use when performing service principal authentication with Azure.
                client-certificate-path: # Path of a PEM certificate file to use when performing service principal authentication with Azure.
                client-certificate-password: # Password of the certificate file.
                username: # Username to use when performing username/password authentication with Azure.
                password: # Password to use when performing username/password authentication with Azure.
                managed-identity-enabled: # Whether to enable managed identity to authenticate with Azure. If true and the client-id is set, will use the client id as user assigned managed identity client id.
              profile:
                tenant-id: # Tenant id for Azure resources.
                subscription-id: # Subscription id to use when connecting to Azure resources.
                cloud-type: AZURE_CHINA # Name of the Azure cloud to connect to.
              resource:
              client:
                application-id: # Represents current application and is used for telemetry/monitoring purposes.
                headers:
                  - name: Custom-Header-Name # The name of the header.
                    values: value1, value2 # List of values of the header.
                write-timeout: # Amount of time each request being sent over the wire.
                response-timeout: # Amount of time used when waiting for a server to reply.
                read-timeout: # Amount of time used when reading the server response.
                connect-timeout: # Amount of time the request attempts to connect to the remote host and the connection is resolved.
                maximum-connection-pool-size: # Maximum connection pool size used by the underlying HTTP client.
                connection-idle-timeout: # Amount of time before an idle connection.
                logging:
                  level: body_and_headers # The level of detail to log on HTTP messages.
                  allowed-header-names: User-Agent # Comma-delimited list of whitelisted headers that should be logged.
                  allowed-query-param-names: parameter1 # Comma-delimited list of whitelisted query parameters.
                  pretty-print-body: true # Whether to pretty print the message bodies.
              proxy:
                type: # Type of the proxy.
                hostname: # The host of the proxy.
                port: # The port of the proxy.
                username: # Username used to authenticate with the proxy.
                password: # Password used to authenticate with the proxy.
                non-proxy-hosts: # A list of hosts or CIDR to not use proxy HTTP/HTTPS connections through.
              retry:
                max-retries: 1 # The maximum number of attempts.
                base-delay: 1s # Amount of time to wait between retry attempts.
                max-delay: 1s # Maximum permissible amount of time between retry attempts.
                mode: FIXED # The retry backoff mode when retrying.
            - name:
              enabled:
              endpoint:


```

**Comment by chenrujun** [comment]
Closing this issue, because we won't do any feature change before 4.0 GA.

**Comment by chenrujun** [comment]
Reopen this issue. To make each property have clear definition.

Here is current design:
```
spring:
  cloud:
    azure:
      credential:
      profile:
      client:
      proxy:
      retry:
      keyvault:
        secret:
          enabled: # Just used to enable SecretClient related beans, no related to PropertySource.
          credential:
          profile:
          resource:
          client:
          proxy:
          retry:
          endpoint:
          service-version:
          property-source-enabled: # Just used to enable PropertySource.
          property-sources:
            enabled:
            credential:
            profile:
            resource:  # Seems this property is not used for now.
              region:    
              resource-group:
              rsource-id:
            client:
            proxy:
            retry:
            endpoint:
            service-version:
            name
            case-sensitive
            secret-keys
            refresh-interval
            
            
            

Features:
1. KeyVault SecretClient related beans.
  1.1. Create KeyVault SecretClient related beans by properties prefixed with "spring.cloud.azure.keyvault.secret".
  1.2. For properties like "credential", "profile", "client", "proxy", "retry" are not configured in "spring.cloud.azure.keyvault.secret.*", "spring.cloud.azure.*" will be used.
  1.3. Set "spring.cloud.azure.keyvault.secret.enabled=false" to disable this feature.
2. KeyVault Secret PropertySource.
  2.1. Inset PropertySource by properties prefixed with "spring.cloud.azure.keyvault.secret.property-sources".
  2.2. For properties like "credential", "profile", "resource", "client", "proxy", "retry", "endpoint", "service-version", If "spring.cloud.azure.keyvault.secret.property-sources[].*" is not configured, "spring.cloud.azure.keyvault.secret.*" will be used.
  2.3. For properties like "credential", "profile", "client", "proxy", "retry" are not configured in "spring.cloud.azure.keyvault.secret.property-sources[].*" and "spring.cloud.azure.keyvault.secret.*", "spring.cloud.azure.*" will be used.
  2.4. Set "spring.cloud.azure.keyvault.secret.enabled=false" to disable this feature.
```
