### ISSUE TITLE
Problems of configured Azure SDK Client bean.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27618]
In Sprig Cloud Azure 4.0, we provided a new feature: configure Azure SDK Clients as bean by the properties in `application.yml`. But now I found a lot of problems about current implementation.

1. Some properties exist in `application.yml` (IDE can provide hint by `spring-configuration-metadata.json`), but does not take effect. It will confuse our customer. For example, `spring.cloud.azure.keyvault.secret.resource`.
2. Some properties can be configured by `XxxClientBuilder`, but can not configured by `application.yml`. For example: `CosmosClientBuilder#userAgentSuffix`, `CosmosClientBuilder#permissions`, etc..
3. Property name is not map to `XxxClientBuilder`'s public method name directly, it may confuse our customer. For example: 
  3.1. We provide property `spring.cloud.azure.keyvault.secret.client`, but SecretClientBuilder has 2 public method with `client`: `SecretClientBuilder#httpClient`, `SecretClientBuilder#clientOptions`.
  3.2. We provide property `spring.cloud.azure.keyvault.secret.retry`, but in `SecretClientBuilder`, it's `SecretClientBuilder#retryPolicy`.
4. `XxxClientBuilder` related property is in the same level with other feature property. For example: 
  4.1. It's better to change
```yml
spring:
  cloud:
    azure:
      cosmos:
        client-telemetry-enabled: # CosmosClientBuilder related property
        populate-query-metrics: # azure-spring-data-cosmos related property
```
to 
```yml
spring:
  cloud:
    azure:
      cosmos:
        cosmos-client-builder:
          client-telemetry-enabled: # CosmosClientBuilder related property
        cosmos-config:
          populate-query-metrics: # azure-spring-data-cosmos related property
```
  4.2. It's better to change 
```yml
spring:
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: # KeyVaultClient related property
          service-version:
          property-source-enabled: # PropertySource related property
          property-sources:
```
to 
```yml
spring:
  cloud:
    azure:
      keyvault:
        secret:
          secret-client-builder:
            endpoint: # KeyVaultClient related property
            service-version:
          property-source:
            property-source-enabled: # PropertySource related property
            property-sources:
```
