### ISSUE TITLE
Getting MessageDispatchingException: Dispatcher has no subscribers, when using multibinders for eventhubs

### ISSUE THREAD

**Issue by rhyashu** [Azure/azure-sdk-for-java#27869]
**Query/Question**
Getting below exception when processing events from a namespace and sending to different event hub in other namespace (ref [Sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/azure-spring-cloud_2.8.0/eventhubs/azure-spring-cloud-stream-binder-eventhubs/eventhubs-multibinders)).

```console
ErrorMessage [payload=org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel '**unknown.channel.name**'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
```

```yaml
    cloud:
     azure:
       msi-enabled: true
       client-id: abcd
       resource-group: eastus2-rg
       subscription-id: 
       

     stream:
       bindings:
         consume-in-0:
           binder: eventhub-1
           destination: datavalids
           group: $Default           
         valid-out-0:
           binder: eventhub-2
           destination: idvalid
         reject-out-0:
           binder: eventhub-2
           destination: idreject
       binders:
        eventhub-1:
          type: eventhub
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    namespace: abc-eastus2-eventhub-1
                    checkpoint-storage-account: premblobsa
                    checkpoint-container: testblob
        eventhub-2:
          type: eventhub
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    namespace: abc-eastus2-eventhub-2
                    checkpoint-storage-account: premblobsa
                    checkpoint-container: testblob
       default:
         producer:
           errorChannelEnabled: true  
         
         
       eventhub:
         bindings:
           consume-in-0:
             consumer:
               checkpoint-mode: MANUAL
               
       function:
         definition: consume;valid;reject;
       poller:
         initial-delay: 0
         fixed-delay: 1000
```
***Why is this not a Bug or a feature Request?***
Not sure if its an issue, just want to check why this error is coming, is there something we are missing in config here?

**Setup (please complete the following information if applicable):**
 - OS: Linux/Windows10, AKS
 - IDE: Eclipse
 - Library/Libraries: [ com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.8.0 ]
 
 **Information Checklist**
We are using streamBridge to sent to multiple output bindings after validating the event:

```java
streamBridge.send("valid-out-0", message.getPayload());
// or
streamBridge.send("reject-out-0", message.getPayload());
```
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@yiliuTo could you please take a look?

/cc @conniey

**Comment by yiliuTo** [comment]
@rhyashu , as I can successfully work with your configuration and version 2.8.0 to "process events from a namespace and sending to different event hub in other namespace", here is my code:
```
    @Autowired
    private StreamBridge streamBridge;

    @Bean
    public Consumer<Message<String>> consume() {
        return message -> {
            Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
            LOGGER.info("New message received: '{}'", message.getPayload());
            checkpointer.success()
                    .doOnSuccess(success -> LOGGER.info("Message '{}' successfully checkpointed", message))
                    .doOnError(error -> LOGGER.error("Exception found", error))
                    .block();
            streamBridge.send("reject-out-0", message);
            LOGGER.info("Forward message: {}.", message.getPayload());
        };
    }
```
Could you provide a minimum sample to help me reproduce this exception, including the pom.xml to show the dependency information and also the critical code of the `consume`, `valid` or `reject` components to show how you define and use them?

**Comment by rhyashu** [comment]
Hi @yiliuTo ,

We are able to process most of the messages too. Out of around 500 messages this was coming for around 30 off cases. And we were missing 30 around messages in the final output as well.

Below is the consume method code:

`
@Bean
	public Consumer<Message<String>> consume() {

		return message ->  {
			LOGGER.info(
			              "New message received : '{}', partition Id: {}, sequence number: {}"
			              , message.getPayload(),
			              message.getHeaders().get(EventHubHeaders.RAW_PARTITION_ID),
			              message.getHeaders().get(EventHubHeaders.SEQUENCE_NUMBER)
			              );
			Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
			OutputEvent eventMessageOut = checkEvent(message.getPayload()); //to check if event is valid or not
			
			if (eventMessageOut.isValidFlag()) {
				streamBridge.send("publishvalid-out-0", eventMessageOut);
			} else {
				streamBridge.send("publishrjct-out-0", eventMessageOut);
			}
			checkpointer.success().doOnSuccess(success -> LOGGER.info("Message successfully checkpointed"))
			  .doOnError(error -> LOGGER.error("Exception found", error)).subscribe();
		};

	}
`

POM:

`

<dependencies>

		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<version>3.4.8</version>
			
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-cloud-stream-binder-eventhubs</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-cloud-starter-eventhubs</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-spring-data-cosmos</artifactId>
			<version>3.13.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-eventhubs</artifactId>
			<version>5.10.0</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-logging-logback</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core</artifactId>
			<version>1.20.0</version>
		</dependency>
`

**Comment by yiliuTo** [comment]
@rhyashu thansk for the response, I will try to reproduce the exception given it occurs occasionally. 

Besides, could you share which boms you import for dependency management and the version you use? especially for Spring Boot and Spring Cloud? I am curently using Spring Boot 2.5.0 and Spring Cloud 2020.0.3. Also if you are using other boms, please share them as well, because I cannot import the two `applicationinsights` libraries now.

So my pom.xml is as below, I omit `azure-spring-cloud-starter-eventhubs` and `azure-messaging-eventhubs` for they haven been imported from `azure-spring-cloud-stream-binder-eventhubs` and the versions are the same as the ones you specify.
```
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.5.0</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>azure-spring-cloud-sample-eventhubs-multibinders</artifactId>
  <groupId>com.azure.spring</groupId>
  <version>1.0.0</version> <!-- {x-version-update;com.azure.spring:azure-spring-cloud-sample-eventhubs-multibinders;dependency} -->
  <name>Azure Spring Cloud Sample Event Hubs Multiple Binders</name>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>2020.0.3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>azure-spring-cloud-dependencies</artifactId>
        <version>2.8.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-cloud-stream-binder-eventhubs</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-logging</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.4.8</version>
      <!-- $NO-MVN-MAN-VER$ -->
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-spring-data-cosmos</artifactId>
      <version>3.13.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core</artifactId>
      <version>1.20.0</version>
    </dependency>
  </dependencies>

```

**Comment by yiliuTo** [comment]
Hi @rhyashu , the [exception of "Dispatcher has no subscribers"](https://github.com/spring-projects/spring-integration/blob/349aad36d8f254b15763b2ffee83653a96832eba/spring-integration-core/src/main/java/org/springframework/integration/dispatcher/UnicastingDispatcher.java#L138) happens when StreamBridge sends messages via a channel while finds no handler for the channel to dispatch messages to. However, reasons that could cause such error could be various, e.g., the destination for the channel doesn't exist, thus I cannot locate the root cause only from publishing/subscribing code. Would it be possible to share a complete example project that could reproduce this exception?

**Comment by yiliuTo** [comment]
@rhyashu , thanks for following. However, as I still failed to reproduce this error with the versions you use, also for reasons why no handlers can be binded to the sending channel could be various, would you share a complete example project that could reproduce this exception?

**Comment by rhyashu** [comment]
Hi @yiliuTo , Will create a sample project and share with you..

**Comment by rhyashu** [comment]
Also updated the version for below:

`
<dependency>
		<groupId>io.projectreactor</groupId>
		<artifactId>reactor-core</artifactId>
		<version>3.4.8</version>
		
</dependency>

<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core</artifactId>
			<version>1.21.0</version>
</dependency>
`

**Comment by jialigit** [comment]
> ill create a sample project and share with you..

Hi, @rhyashu , what about the sample project progress now?

**Comment by rhyashu** [comment]
We created a sample project but we are facing issues with checkpointer header coming as null even though the checkpointing mode is set as Manual.

**Comment by jialigit** [comment]
> We created a sample project but we are facing issues with checkpointer header coming as null even though the checkpointing mode is set as Manual.

@rhyashu  Can you link your sample repo, and let's figure it out together?

**Comment by rhyashu** [comment]
hi @jialigit ,

can you try the sample project from here?
[https://github.com/rhyashu/cloudstream-multibinder](url)

**Comment by jialigit** [comment]
@rhyashu , Thank you for your information. I am looking into it.

**Comment by jialigit** [comment]
@rhyashu , for the NPE issue, I think It's because of the config indentation problem. 
```
spring:
    cloud:
        stream:
            eventhub:
                bindings:
                    consume-in-0:
                        consumer:
                            checkpoint-mode: MANUAL
```
