### ISSUE TITLE
azure-servicebus-jms-spring-boot-starter remove hyphens from properties

### ISSUE THREAD

**Issue by MartinGolding515** [Azure/azure-sdk-for-java#28907]
**Is your feature request related to a problem? Please describe.**
injecting spring properties from env vars works locally but not in kubernetes because the names include hyphens.

this is true for connection-string and pricing-tier

The same applies for any of the azure java starters using hyphens. 

**Describe the solution you'd like**
remove hyphens or replace with underscore. Alternatively add new alias' so the code is backwardly compatible.

**Describe alternatives you've considered**
workaround is to include them in application.properties / .yaml and reference an env var with a different name:
```yaml
spring:
  jms:
    servicebus:
      pool:
       idle-timeout: 20000
       enabled: 'true'
      connection-string: ${SERVICEBUS_CONNECTION_STRING}
      pricing-tier: ${SERVICEBUS_PRICING_TIER}
```
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
Hi @MartinGolding515, the Spring Boot properties support [relaxed binding](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding), which means you can use kebab case or camel case when defining the properties in your application `.properties` or `.yaml` files. How about trying 
```yaml
spring:
  jms:
    servicebus:
      connectionString: xxx
      pricingTier: xxx
```

**Comment by MartinGolding515** [comment]
Hi @saragluna , thanks. That works locally and on kubernetes using env vars directly: 

```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_JMS_SERVICEBUS_CONNECTIONSTRING
          value: "Endpoint=xxx"
        - name: SPRING_JMS_SERVICEBUS_PRICINGTIER
          value: "xxx"
```
