### ISSUE TITLE
[FEATURE REQ] Allow multiple ClientRegistrations for Azure AD B2C

### ISSUE THREAD

**Issue by lorenzo-b-way** [Azure/azure-sdk-for-java#29662]
As required by the application properties and by the execution of the code, this library allows you to register only one B2C client.
That is to say I can only use one set of properties:

```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: XXXXXXXXXXXXXXXX
          credential:
            client-id: XXXXXXXXXXXXXXXX
            client-secret: XXXXXXXXXXXXXXXX
          user-flows: 
            sign-up-or-sign-in: XXXXXXXXXXXXXXXX
```

Spring manages multiple clients, in my case, it would be useful to be able to use different B2C clients in the same application.

```yaml
azure-ad-b2c-first
  authorization-uri: XXXXXXXXXXXXXXXX
  token-uri: XXXXXXXXXXXXXXXX
  jwk-set-uri: XXXXXXXXXXXXXXXX
```  

```yaml
azure-ad-b2c-second
  authorization-uri: XXXXXXXXXXXXXXXX
  token-uri: XXXXXXXXXXXXXXXX
  jwk-set-uri: XXXXXXXXXXXXXXXX
```

Especially I should specify a different user-flows for each application

```yaml
user-flows: 
            sign-up-or-sign-in: XXXXXXXXXXXXXXXX

user-flows: 
            sign-up-or-sign-in: YYYYYYYYYYYYYYYYY
```

Has this possibility ever been considered? 

Spring boot manages multiple properties for provider and registration by creating a map but this library always manages one at a time, always creating a map with only one element

**Comment by moarychan** [comment]
Recommend to use this class [AadB2cClientRegistrationRepository](https://github.com/Azure/azure-sdk-for-java/blob/5bc550c9a5de4f8ee93a5b3141500ee34be3850d/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aadb2c/implementation/AadB2cClientRegistrationRepository.java#L19-L18) to custom your own client registration repository that will contain multiple client registration for your scenario, I will output a sample for this scenario.

**Comment by moarychan** [comment]
Hi @lorenzo-b-way  sorry for the late update!

I'm preparing to implement this feature request, and I want to know more about your scenario, it will be very helpful for the final concrete implementation.
Could you help provide details for the multiple sign-in processes in your application?

**Comment by lorenzo-b-way** [comment]
Hi @moarychan, it's quite simple.
I have two B2C contexts in the same application.
Two different users need to login to the same BE but using different B2C configurations as explained in my first post, two different login forms point to two flows .
Obviously the login and logout flow will have to refer to different configurations as shown in the example properties.

As you know, now the application accepts only one set of parameters for:

```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: XXXXXXXXXXXXXXXX
          credential:
            client-id: XXXXXXXXXXXXXXXX
            client-secret: XXXXXXXXXXXXXXXX
          user-flows: 
            sign-up-or-sign-in: XXXXXXXXXXXXXXXX
```

 and it is not possible to use multiples

**Comment by moarychan** [comment]
I have the below proposal for this feature, welcome to discuss it.

## 1. User Stories

As a Spring user of Spring Cloud Azure Starter AD B2C, I want to integrate the below scenarios into my application:

### 1.1 Use multiple sign-in user flows of AD B2C for different dimensions of users in the organization

   The different sign-in user flow may configure the different multifactor, the student can use an email as an authenticator and the token lifetime may be longer than a teacher; a teacher may require a more secure method, `SMS or phone call`, and use a shorter expiration time to ensure the security.
   
   ![userflow-config](https://user-images.githubusercontent.com/19926623/213337368-0ed7cf71-bffc-4d85-9fc4-ac6258e53868.png)

   Combining the configuration of the AD B2C user flow on Azure Portal, differentiated configurations are very easy to manage.
   
   ![user-flow-different](https://user-images.githubusercontent.com/19926623/213337488-c84d563e-4b20-4534-9ff6-7cbe6545630d.png)


### 1.2 Integrate the social accounts login and sign-in user flow of AD B2C on the login page

   Social account login is very convenient, giving users multiple choices, and quickly completing verification and accessing resources. Before initiating the sign-in user flow in AD B2C, customers want to choose the relevant social account to log in directly.
   
   ![skip-userflow-login-page](https://user-images.githubusercontent.com/19926623/213337559-af63ff05-26d6-4826-aa20-2888f3ffafb4.png)


If I can achieve these, I can refine the management process of each user identity to achieve more accurate control and more secure management.

## 2. Goals

### 2.1 Goals

#### 2.1.1 Support multiple instances of sign-in user flows registration from different AD B2C tenants

By default implementation, one application will be registered with user flow instances.

```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: https://xxxb2c.b2clogin.com/xxxadb2c.onmicrosoft.com
          credential:
            client-id: xxx-client-id
            client-secret: xxx
          login-flow: sign-up-or-sign-in
          logout-success-url: http://localhost:8080/login
          user-flows:
            password-reset: B2C_1_passwordreset
            profile-edit: B2C_1_profileediting
            sign-up-or-sign-in: B2C_1_signuporsignin
```

After this feature goes live, customers will have the below program ability to configure an AD B2C application via a `AadB2cClientRegistrationRepositoryBuilderCustomizer ` bean, it's used to convert the user flow instances to OAuth2 clients for Spring Security. 

The below code will configure the user flow instances with different AD B2C application registration, some user flow instances are from the second AD B2C, and other user flow instances are from the third AD B2C.

```java
@Bean
AadB2cClientRegistrationRepositoryBuilderCustomizer secondB2CTenantRegistrationRepositoryBuilderCustomizer() {
        return builder -> {
            Map<String, String> userFlows = new HashMap<>();
            userFlows.put("sign-up-or-sign-in", "B2C_1_signuporsignin2");
            builder.aadB2cClientRegistration()
                   .clientId("xxx")
                   .clientSecret("xxx")
                   .baseUri("xxx")
                   .loginFlow("sign-up-or-sign-in")
                   .userFlows(userFlows);
        };
}

@Bean
AadB2cClientRegistrationRepositoryBuilderCustomizer thirdB2CTenantRegistrationRepositoryBuilderCustomizer() {
        return builder -> { };
}
```

Then the default login page will show the two entrances for different users to log in.

![multi-sign-in-userflow](https://user-images.githubusercontent.com/19926623/213337656-829f1ee4-d7df-4373-b6ea-668d464ecaf6.png)

#### 2.1.2 Support the social accounts login and AD B2C user flow login with the same priority on the login page

By default implementation, the application can not integrate with other social accounts, it just can integrate them in a special user flow instance.

After this feature goes live, customers can use the OAuth2 Client properties to configure the social accounts, these OAuth2 clients will be merged with the AD B2C user flow instances, and finally, they will be shown the login links with the same priority on the login page. The OAuth2 Client properties like those below:

```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: https://xxxb2c.b2clogin.com/xxxadb2c.onmicrosoft.com
          credential:
            client-id: xxx-client-id
            client-secret: xxx
          login-flow: sign-up-or-sign-in
          logout-success-url: http://localhost:8080/login
          user-flows:
            password-reset: B2C_1_passwordreset
            profile-edit: B2C_1_profileediting
            sign-up-or-sign-in: B2C_1_signuporsignin

  security:
    oauth2:
      client:
        provider:
          customer-provider:
            authorization-uri: https://xx/oauth2/v2.0/authorize
            token-uri: https://xxx/oauth2/v2.0/token
            jwk-set-uri: https://xxx/discovery/v2.0/keys
        registration:
          google:
            client-id: xxx.apps.googleusercontent.com
            client-secret: xxx
          github:
            client-id: xxx
            client-secret: xxx
          B2C_1_signuporsignin:
            provider: customer-provider
            client-name: Custom
            client-id: xxx
            client-secret: xxx
            scope: xxx, openid, offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/
            authorization-grant-type: authorization_code
```

Then the default login page will show the four entrances for different users to log in.

![goal-muti-social-login](https://user-images.githubusercontent.com/19926623/213337740-d12c05b6-a510-42a4-bcaa-65b34e085d8b.png)


### 2.2 Non-Goals

#### 2.2.1 Does not include Azure AD Starter functionality
