### ISSUE TITLE
[BUG] DP Codegen not generating credential methods on client builders

### ISSUE THREAD

**Issue by chrissmiller** [Azure/azure-sdk-for-java#31100]
**Describe the bug**
Autorest generation for Dataplane is not generating credential methods on client builders, even when security and security-scopes are specified.

**To Reproduce**
Follow guide [here](https://github.com/Azure/azure-sdk-for-java/wiki/Protocol-Methods-Quickstart-with-AutoRest) for DP codegen for Java with Autorest, using below README (linking to valid input files available [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devcenter/data-plane/Microsoft.DevCenter/preview/2022-03-01-preview) in official spec repo). Observe that no credential methods are added to the client builders.

***Code Snippet***
Add the code snippet that causes the issue.

``` yaml
input-file:
  - C:/Users/chrismiller/source/repos/azure-devtest-center/src/sdk/specification/devcenter/data-plane/Microsoft.DevCenter/preview/2022-03-01-preview/devcenter.json
  - C:/Users/chrismiller/source/repos/azure-devtest-center/src/sdk/specification/devcenter/data-plane/Microsoft.DevCenter/preview/2022-03-01-preview/devbox.json
  - C:/Users/chrismiller/source/repos/azure-devtest-center/src/sdk/specification/devcenter/data-plane/Microsoft.DevCenter/preview/2022-03-01-preview/environments.json
payload-flattening-threshold: 2
public-clients: true
security: AADToken
security-scopes: https://devcenter.azure.com/.default
```

**Expected behavior**
Credential methods are available on client builders for authentication

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Win 11 Enterprise
 - IDE: [e.g. IntelliJ] VS 2022 Preview
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] N/A (new library)
 - Java version: [e.g. 8] openjdk 17.0.4 2022-07-19 LTS
 - @autorest\java version: 4.1.3

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added
