### ISSUE TITLE
[QUERY] Correctly configure spring-cloud-azure-starter-keyvault-secrets for client ID/secret authentication

### ISSUE THREAD

**Issue by zpdeering** [Azure/azure-sdk-for-java#32006]
**Query/Question**
I am having an issue configuring the spring-cloud-azure-starter-keyvault-secrets to use client ID/secret authentication to the key vault. Following the instructions at https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#add-key-vault-configuration-to-the-app, I am setting the following properties in my application.yml file (with placeholders for this submission):
```
spring:
   cloud:
      azure:
         keyvault:
            secret:
               property-sources:
                  - endpoint: ${keyvaultUri}
                    profile:
                       tenant-id: ${tenantId}
                    credential:
                      client-id: ${clientId}
                      client-secret: ${clientSecret}
```
I am getting the following error:
`com.azure.core.exception.ClientAuthenticationException: The current credential is not configured to acquire tokens for tenant ${tenantId}. To enable acquiring tokens for this tenant add it to the AdditionallyAllowedTenants on the credential options, or add "*" to AdditionallyAllowedTenants to allow acquiring tokens for any tenant. See the troubleshooting guide for more information. https://aka.ms/azsdk/java/identity/multitenant/troubleshoot`

However, the tenant ID matches the one that the service principal was created under. Additionally, I'm not building the DefaultAzureCredentials and letting the Spring Boot autoconfiguration do it. Looking for guidance on either how to manually wire the Azure Credentials so I can add that AdditionallyAllowedTenants block, or what I should be doing differently in the plugin configuration in order to make this work.

***Why is this not a Bug or a feature Request?***
I assume that I am doing something wrong or just missing something, so I do not believe this is a bug in the code.

**Setup (please complete the following information if applicable):**
 - OS: macOS 13 (also appears on AKS in an openjdk:11-jre-slim container) 
 - IDE: IntelliJ IDEA
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-keyvault-secrets:4.4.1, org.springframework.boot:spring-boot-starter-parent:2.7.5
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Hi @zpdeering thank you for reaching out to us via this github issue.  @chenrujun could you please follow up?

**Comment by backwind1233** [comment]
> Hi @zpdeering thank you for reaching out to us via this github issue. @chenrujun could you please follow up?

Hi @joshfree, for any issue related to azure spring and keyvault, please assign to me while doing issues triage. 

Hi @zpdeering, I will follow up your question.

**Comment by chenrujun** [comment]
Hi, @zpdeering 

I have some questions about your app:
1. Is the **${clientId}** a multi-tenant app?
2. Is the **${clientId}** belong to the **${tenantId}**? I think the answer is yes as you said `tenant ID matches the one that the service principal was created under`.
3. Is the **${keyvaultUri}** belong to the **${tenantId}**?

**Comment by zpdeering** [comment]
Hi @chenrujun. The AAD app ${clientId} is not a multitenant app, and it does belong to the tenant ${tenantId}. The Key Vault is under a child tenant of the parent tenant with ${tenantId}.

**Comment by chenrujun** [comment]
@zpdeering 

Thank you for your quick response.

Here is my current understanding: There are 2 tenants: **teannt-1** and **tenant-2**:

1. **tenant-1** is the parent of **tenant-2**.
2. The **client-id** used in your app belong to **tenant-1**. Let's name it **client-1**.
3. The **key vault** used in your app belong to **tenant-2**. Let's name it **key-vault-2**.

I'll try to reproduce the problem after you confirmed above items.

**Comment by chenrujun** [comment]
@zpdeering 

How did you run this step:

> Configure the Key Vault to allow get and list operations from that managed identity.

In my side, when the client-id and the keyvault belong to different tenant, this step failed with error like this:

```shell
$ az keyvault set-policy   --name ${keyvault-name}   --spn ${client-1} --secret-permissions get list
Unable to find user with spn '${client-1}'
Unable to get object id from principal name.
```

**Comment by zpdeering** [comment]
@chenrujun 
So truthfully, I did it through the Portal UI because we had already set these up before trying to get this Spring Boot dependency to work. I did not have that issue though - our subscription "tenant-2" can browse the full AAD from "tenant-1" allowing us to use those to set policy.

And for the record, this all works fine with the older (pre-Azure Identity auth changes mentioned at https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/BREAKING_CHANGES.md) dependencies, so it's not like it's never worked.

**Comment by zpdeering** [comment]
@chenrujun so I actually managed to get this to work this morning - I had confused my tenant IDs and had been using the tenant-2 ID and not the tenant-1 ID in the Spring Boot parameters.

**Comment by chenrujun** [comment]
@zpdeering 

Thank you for your feedback.

> I actually managed to get this to work this morning - I had confused my tenant IDs

I have some questions: 
1. What's current status? Did you still use **client-1** (belong to **tenant-1**) to access **key-vault-2** (belong to **tenant-2**) ?
2. `our subscription "tenant-2" can browse the full AAD from "tenant-1" allowing us to use those to set policy.` Is it right for now?

**Comment by zpdeering** [comment]
@chenrujun 
Yes, sorry - I had misrepresented what I was putting into my application.yml because I had tenant-1's ID and tenant-2's ID confused. So what I had originally was actually:
```
spring:
   cloud:
      azure:
         keyvault:
            secret:
               property-sources:
                  - endpoint: key-vault-2-uri
                    profile:
                       tenant-id: tenant-2-id
                    credential:
                      client-id: client-1-id
                      client-secret: client-1-secret
```

And once I updated tenant-id to be tenant-1-id, it worked.
