### ISSUE TITLE
[FEATURE REQ] Simplify the connection related properties for blob checkpoint store in Spring Cloud Azure Event Hubs libraries

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#32035]
## Context
When using Storage Blob as the checkpoint store in Spring Cloud Azure Event Hubs libraries, we provide multiple connection related properties to specify the target server entity to connect to. However, in some cases, the usage of those properties may be redundant and cloud be simplified. 

The default and simplest usage case is that:
```yaml
spring:
  cloud:
    azure:
      eventhubs:
        processor:
          checkpoint-store:
            container-name: ...
            account-name: ...
            account-key: ....
```

However, when there are requests to specify the Storage endpoint, e.g., the server is in Azure China cloud, then developers need to provide properties like:
```yaml
spring:
  cloud:
    azure:
      eventhubs:
        processor:
          checkpoint-store:
            container-name: ...
            account-name: ...
            endpoint: https://<account-name>.blob.core.chinacloudapi.cn
            account-key: ....
```
where the `endpoint` property actually contains the information of `account-name` but we still require the `account-name` property to be configured.

Similar cases happen for the property of `connection-string`, the Storage connection string contains information about the endponit, account name and others. But let's still use the use case that a developer wants to connect to a Storage server in Azure China cloud, then required properties are:
```yaml
spring:
  cloud:
    azure:
      eventhubs:
        processor:
          checkpoint-store:
            container-name: ...
            account-name: ...
            endpoint: https://<account-name>.blob.core.chinacloudapi.cn
            connection-string: ...
```
or 
```yaml
spring:
  cloud:
    azure:
      profile:
        cloud-type: azure_china
      eventhubs:
        processor:
          checkpoint-store:
            container-name: ...
            account-name: ...
            connection-string: ...
```
where multiple properties are required but provide redundant information.

## Goal
We should simplify the required properties for the above cases and avoid that developers need to configure multiple properties but provide similar information .
