### ISSUE TITLE
[FEATURE REQ] Simplify properties of specificying Azure Cloud for Spring Cloud Azure Event Hubs/Service Bus libraries

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#32034]
## Context
When using the token credential to connect Event Hubs in non-global Azure cloud via Spring Cloud Azure Event Hubs libraries, currently we require two properties to specify the cloud information, which may be redundant. Taking using the service principal to connection Event Hubs on Azure China as example, the least properties are:
```yaml
spring:
  cloud:
    azure:
      credential:
        client-id: ...
        client-secret: ...
      profile:
        tenant-id: ...
        cloud-type: azure_china
      eventhubs:
        processor:
          checkpoint-store:
            container-name: ...
            account-name: ...
        namespace: ....
        domain-name: servicebus.chinacloudapi.cn
```
While the property `spring.cloud.azure.profile.cloud-type` and `spring.cloud.azure.eventhubs.domain-name` contain similar information about the cloud type, but are both requried now. Thus we may consider to simplify the configuration to require only one property for cloud. Same for Spring Cloud Azure Service Bus libraries.

## Goal
Simplify the required property for cloud information, the expected number of required cloud-related property should be one.

**Comment by yiliuTo** [comment]
The domain-name property should be optional for both Event Hubs and Service Bus. So the required configuration for connecting Event Hubs / Service Bus in non-public Azure cloud via token credential should be:
```yaml
spring:
  cloud:
    azure:
      credential:
        client-id: ...
        client-secret: ...
      profile:
        tenant-id: ...
        cloud-type: ...
      eventhubs: # or servicebus:
        namespace: ....
```
With the above configuration, `domain-name` property will be automatically generated according to the `cloud-type`.

Additionally, the domain-name can also be configured and if so, the configured value will override the one generated from cloud-type
