### ISSUE TITLE
[BUG] Message header 'source-type' should be eventhubs not kafka when using Spring Cloud Azure EventHubs binder

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#32777]
**Describe the bug**
When the partition properties are configured, a new header `source-type` will be set with the value `kafka`.

**To Reproduce**
Use this sample [eventhubs-binder](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder)
Use the below configuration:
```yml
spring:
  cloud:
    azure:
      eventhubs:
        connection-string: xxx
        processor:
          checkpoint-store:
            container-name: xxx-containter
            account-name:  xxx-storage
            account-key: xxx-key
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: xxx
          group: $Default
        supply-out-0:
          destination: xxx
          producer:
            partition-key-expression: payload
            partition-count: 100
      eventhubs:
              bindings:
                consume-in-0:
                  consumer:
                    checkpoint:
                      mode: MANUAL
```

**Expected behavior**
The header `source-type` should take a non-kafka value, maybe it can be removed.

**Setup (please complete the following information):**

 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-eventhubs:4.5.0
 - Java version: 17
 - Frameworks: Spring Boot 2.7.7
