### ISSUE TITLE
Does auto-creation of service bus topic/subscription feature work with Endpoint connection string?

### ISSUE THREAD

**Issue by blackr1234** [Azure/azure-sdk-for-java#34823]
## Query/Question

According to this documentation (for Spring Cloud Azure `4.4.1` at the time of writing):

[Resource Provision](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#resource-provision-2)

> Service bus binder supports provisioning of queue, topic and subscription, users could use the following properties to enable provisioning.
> 
> ```yaml
> spring:
>   cloud:
>     azure:
>       credential:
>         tenant-id: ${AZURE_TENANT_ID}
>       profile:
>         subscription-id: ${AZURE_SUBSCRIPTION_ID}
>       servicebus:
>         resource:
>           resource-group: ${AZURE_SERVICEBUS_RESOURECE_GROUP}
>     stream:
>       servicebus:
>         bindings:
>           <binding-name>:
>             consumer:
>               entity-type: ${SERVICEBUS_CONSUMER_ENTITY_TYPE}
> ```

Now, consider my config below:

```yaml
spring:
  cloud:
    azure:
      servicebus:
        connection-string: Endpoint=sb://...
    stream:
      function:
        definition: consume;supply # function style methods in Java code
      bindings:
        consume-in-0:
          destination: expect-auto-create-topic
          group: expect-auto-create-subscription
          binder: servicebus
        supply-out-0:
          destination: expect-auto-create-topic
          binder: servicebus
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: true
          supply-out-0:
            producer:
              entity-type: topic
```

As per my testing, by specifying just the connection string (not following the doc), my application does not create topic and subscription for me.

**Question 1: Is this expected?**

However, as far as I know, the `ServiceBusAdministrationClient` class (from transitive dependency `com.azure:azure-messaging-servicebus`) is capable of creating topics and subscriptions with just a connection string with a shared access policy on namespace level.

```java
final ServiceBusAdministrationClient administrationClient =
  new ServiceBusAdministrationClientBuilder()
    .connectionString("Endpoint=sb://...") // connection string with a shared access policy on namespace level
    .buildClient();

administrationClient.createTopic("topic-name");
administrationClient.createSubscription("topic-name", "subscription-name");
```

**Question 2: Given the Java code above, could you explain why by just providing the connection string alone in my config file does not automatically create topics and subscriptions? It is a bug / not technically possible / simply currently not supported?**

**Question 3: A probably irrelevant question: Could you explain the purpose of the `com.azure.spring:spring-cloud-azure-starter-servicebus` library?**

---

## Why is this not a Bug or a feature Request?

Documentation does not mention it will work. So probably there is only 1 allowed way (in config) to trigger automatic creation of topics and subscriptions.

---

## Setup

- Microsoft OpenJDK `11`
- Dependency management
  - `spring-boot-dependencies 2.7.1`
  - `spring-cloud-dependencies 2021.0.3`
  - `spring-cloud-azure-dependencies 4.7.0`
    - `4.4.0` or above should have fixed the auto-creation bug
      - #30324
      - #30722
- Dependencies
  - `spring-boot-starter-web` (managed version)
  - `com.azure.spring:spring-cloud-azure-stream-binder-servicebus` (managed version)

Note: No dependency on `com.azure.spring:spring-cloud-azure-starter-servicebus`.

---

 ## Information Checklist
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Netyyyy** [comment]
Hi @blackr1234 , Thank you for the reporting.
For Question1:
If you want to auto-create topic and sub, please add the following properties:
```yaml
spring:
  cloud:
    azure:
      profile:
        subscription-id: xxx
      servicebus:
        resource:
          resource-group: xxx
        namespace: xxx
```

For Question2:
We use `ServiceBusChannelResourceManagerProvisioner` not `ServiceBusAdministrationClient` to auto-create, it is simply currently not supported.

For Question3:
`com.azure.spring:spring-cloud-azure-starter-servicebus` enables you to send and receive messages with the Service Bus Java SDK client library with Spring Boot features.

**Comment by blackr1234** [comment]
Thanks @Netyyyy for your reply. I guess it will require a feature request to get it then.

Moreover, may I also ask a follow-up question regarding auto-create subscription in ASB.
I have such a use case below:

I have multiple horizontally scaled applications that are Spring Cloud Config clients. Each of the instances of these applications needs to have a separate subscription in the same topic in order for it to receive config refresh messages from the Spring Cloud Config server.

I don't care about the subscription name. It just has to be a unique one.
Is it possible to achieve it with only config properties?
Thank you.

**Comment by Netyyyy** [comment]
> 
Hi @blackr1234 ,
It can't randomly generate subscription names without additional codes, but if you configure each sub name below the same topic and it could be auto-created.

client1:
```yaml
...
      bindings:
        consume-in-0:
          destination: expect-auto-create-topic
          group: sub1
        supply-out-0:
          destination: expect-auto-create-topic
...
```
client2:
```yaml
...
      bindings:
        consume-in-0:
          destination: expect-auto-create-topic
          group: sub2
        supply-out-0:
          destination: expect-auto-create-topic
...
```
