### ISSUE TITLE
[BUG] Resource Server configuration for ad b2c is override by Client Configuration

### ISSUE THREAD

**Issue by remybd** [Azure/azure-sdk-for-java#34909]
**Describe the bug**
I'm trying to migrate my application from spring boot 2.7 to spring boot 3. It imply migrating azure cloud sdk to 5.

I'm using azure ad b2c library to connect my backend to my azure b2c. It's only a resource server consume by an SPA.
I just need to validate the JWT token receive by my API. Following the documentation of resource server configuration does not work.
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-security-support?tabs=SpringCloudAzure5x#usage-3-accessing-a-resource-server

Compare to the documentation, we need to add `enabled: true` and the `user-flows` else the url to contact the ad b2c contain a null value.
But when we add a `user-flows`, the client configuration is automatically configure and take the priority on the resource server.

So either we have a user flow configure and the Client Configuration is activated or we don't have a user flow, but in this case the url to contact the ad b2c will be wrong with null inside because it needs the user flow.

For more information, it all start from a request for documentation on this thread https://github.com/Azure-Samples/azure-spring-boot-samples/issues/551 

For information, I have a custom domain on my azure b2c that is used in the token.

***Exception or Stack Trace***
when no user flows
``
2023-05-12T11:38:04.215+08:00 DEBUG 35908 --- [nio-8080-exec-1] o.s.web.client.RestTemplate              : HTTP GET https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a*****/null/v2.0/.well-known/openid-configuration
``

when user flow, no more call to openid-configuration, instead it try to make my backend login
``
2023-05-12T11:39:54.545+08:00 DEBUG 35592 --- [nio-8080-exec-4] o.s.s.web.DefaultRedirectStrategy        : Redirecting to http://localhost:8080/oauth2/authorization/B2C_1_Datx_SignIn
``
```
2023-05-12T11:39:54.578+08:00 DEBUG 35592 --- [nio-8080-exec-6] o.s.s.web.DefaultRedirectStrategy        : Redirecting to https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a*****/oauth2/v2.0/authorize?response_type=code&client_id=41e8ee56-0d5b-4fed-a36e-ecf1189****&scope=41e8ee56-0d5b-4fed-a36e-ecf11890****%20openid%20offline_access&state=*******************************%3D&redirect_uri=http://localhost:8080/login/oauth2/code/&nonce=*******************************

```

**To Reproduce**
You can reuse the azure spring boot samples.
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-resource-server
Follow all the readme to have a configuration working with springboot 2.7 and azure-cloud 4.

Then, update the versions in the pom to go on spring boot 3 and spring cloud 5.1
I just reuse the configuration for the profile `spring-cloud-azure-5.x` that is in the pom.
``
<properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <java.version>17</java.version>
        <version.spring.boot>3.0.5</version.spring.boot>
        <version.spring.cloud>2022.0.2</version.spring.cloud>
        <version.spring.cloud.azure>5.1.0</version.spring.cloud.azure>
        <version.thymeleaf-extras-springsecurity6>3.1.1.RELEASE</version.thymeleaf-extras-springsecurity6>
        <version.maven-surefire-plugin>2.22.0</version.maven-surefire-plugin>
        <mockito.version>4.8.1</mockito.version>
      </properties>
``

Just updating the version should make it stop working.

Here is my configuration
````
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: "74aeca07-39b9-4721-8b96-428a********"
          app-id-uri: "41e8ee56-0d5b-4fed-a36e-ecf1189****"         # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          credential:
            client-id: "41e8ee56-0d5b-4fed-a36e-ecf1189****"           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: "https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a******"             # Such as: https://xxxxb2c.b2clogin.com
          user-flows:
            sign-up-or-sign-in: B2C_1_Datx_SignIn
````

***Code Snippet***
I went in the code and from my understanding, the problem come from the condition apply on the AadB2cOAuth2ClientConfiguration

``
@Conditional(AadB2cConditions.ClientRegistrationCondition.class)
``
is apply on `AadB2cOAuth2ClientConfiguration`

In `ClientRegistrationCondition` there is no possibility to differentiate between Resource Server flow and Client flow.
``
public static final class ClientRegistrationCondition extends SpringBootCondition {

        @Override
        public ConditionOutcome getMatchOutcome(final ConditionContext context,
                                                final AnnotatedTypeMetadata metadata) {
            ConditionMessage.Builder message = ConditionMessage.forCondition(
                "AAD B2C OAuth 2.0 Clients Configured Condition");
            AadB2cProperties aadb2CProperties = getAadB2cProperties(context);
            if (aadb2CProperties == null) {
                return ConditionOutcome.noMatch(message.notAvailable("aad b2c properties"));
            }

            if (CollectionUtils.isEmpty(aadb2CProperties.getUserFlows())
                && CollectionUtils.isEmpty(aadb2CProperties.getAuthorizationClients())) {
                return ConditionOutcome.noMatch(message.didNotFind("registered clients")
                                                       .items(KEY_OF_USER_FLOWS, "authorization-clients"));
            }

            StringBuilder details = new StringBuilder();
            if (!CollectionUtils.isEmpty(aadb2CProperties.getUserFlows())) {
                details.append(getConditionResult(KEY_OF_USER_FLOWS, aadb2CProperties.getUserFlows()));
            }
            if (!CollectionUtils.isEmpty(aadb2CProperties.getAuthorizationClients())) {
                details.append(getConditionResult("authorization-clients",
                    aadb2CProperties.getAuthorizationClients()));
            }
            return ConditionOutcome.match(message.foundExactly(details.toString()));
        }
    }
``

In the azure ad library `ClientRegistrationCondition` (not the b2c), there is other conditions
``
@Override
    public ConditionOutcome getMatchOutcome(ConditionContext context, AnnotatedTypeMetadata metadata) {
        ConditionMessage.Builder message = ConditionMessage.forCondition("AAD Application Client Condition");
        AadAuthenticationProperties properties =
            Binder.get(context.getEnvironment())
                  .bind("spring.cloud.azure.active-directory", AadAuthenticationProperties.class)
                  .orElse(null);
        if (properties == null) {
            return ConditionOutcome.noMatch(
                message.notAvailable("AAD authorization properties(spring.cloud.azure.active-directory" + ".xxx)"));
        }

        // Bind properties will not execute AADAuthenticationProperties#afterPropertiesSet()
        AadApplicationType applicationType = Optional.ofNullable(properties.getApplicationType())
                                                     .orElseGet(AadApplicationType::inferApplicationTypeByDependencies);
        if (applicationType == null || applicationType == RESOURCE_SERVER) {
            return ConditionOutcome.noMatch(
                message.because("Resource server does not need client registration."));
        }
        return ConditionOutcome.match(
            message.foundExactly("spring.cloud.azure.active-directory.application-type=" + applicationType));
    }
``

In particular, an option to force the applicationType
``
if (applicationType == null || applicationType == RESOURCE_SERVER) {
            return ConditionOutcome.noMatch(
                message.because("Resource server does not need client registration."));
        }
``

**Expected behavior**
Be able to setup a resource server configuration without client login flow

It could be good to continue to be able to setup Resource Server configuration.
The same option than in azure ad library will do the job I think : `applicationType`

Thanks

**Comment by Netyyyy** [comment]
Hi @remybd , Thank you for reporting the issue.
We have received your submission and will take it into consideration. We appreciate your input and will review this matter ASAP.
Please feel free to provide any conditional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by remybd** [comment]
Hello,

Any news of if the bug is valid or not ?
Any potential bypass ?
Any way to help ?

Thanks

**Comment by Netyyyy** [comment]
Hi @remybd , sorry for the late reply. 
After investigation, here are some suggestions may be helpful for Spring Boot 3:
1. without user-flows

Property:
```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
          app-id-uri: https://xxxx.xxxx.com/ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx          # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          credential:
            client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: https://xxxx.b2clogin.com             # Such as: https://xxxxb2c.b2clogin.com
```

WebSecurityConfiguration.class
```java
@Configuration(proxyBeanMethods = false)
@EnableWebSecurity
@EnableMethodSecurity
public class WebSecurityConfiguration {

    @Bean
    SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        JwtAuthenticationConverter authenticationConverter = new JwtAuthenticationConverter();
        JwtGrantedAuthoritiesConverter jwtGrantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
        jwtGrantedAuthoritiesConverter.setAuthorityPrefix("APPROLE_");
        jwtGrantedAuthoritiesConverter.setAuthoritiesClaimName("roles");
        authenticationConverter.setJwtGrantedAuthoritiesConverter(jwtGrantedAuthoritiesConverter);
        // @formatter:off
        http.authorizeHttpRequests((requests) -> requests.anyRequest().authenticated())
            .oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(authenticationConverter);
        // @formatter:on
        return http.build();
    }
}
```

Get access-token by:
```cmd
curl -H "Content-Type: application/x-www-form-urlencoded" -d 'grant_type=client_credentials&client_id=<aad-b2c-web-app-client-id>&scope=<app-id-uri>/.default&client_secret=<aad-b2c-web-app-client-secret>' 'https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token'
```

2. with user-flows

Property:
```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
          app-id-uri: https://xxxx.xxxx.com/ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx          # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          credential:
            client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: https://xxxx.b2clogin.com             # Such as: https://xxxxb2c.b2clogin.com
          user-flows:
            sign-up-or-sign-in: USER_FLOW_NAME
```

WebSecurityConfiguration.class
```java
@Configuration(proxyBeanMethods = false)
@EnableWebSecurity
@EnableMethodSecurity
public class WebSecurityConfiguration {

    @Bean
    SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        JwtAuthenticationConverter authenticationConverter = new JwtAuthenticationConverter();
        JwtGrantedAuthoritiesConverter jwtGrantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
        jwtGrantedAuthoritiesConverter.setAuthorityPrefix("APPROLE_");
        authenticationConverter.setJwtGrantedAuthoritiesConverter(jwtGrantedAuthoritiesConverter);
        // @formatter:off
        http.authorizeHttpRequests((requests) -> requests.anyRequest().authenticated())
            .oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(authenticationConverter);
        // @formatter:on
        return http.build();
    }
}
```

Get access-token by:
```cmd
curl -H "Content-Type: application/x-www-form-urlencoded" -d 'grant_type=client_credentials&client_id=<aad-b2c-web-app-client-id>&scope=<app-id-uri>/.default&client_secret=<aad-b2c-web-app-client-secret>' 'https://xxxx.b2clogin.com/<domain-name>/<user-flow-name>/oauth2/v2.0/token'
```

**Comment by remybd** [comment]
Hello

Thanks for your answer.
I have tried the first solution (because I don't want user flow)
It seems the problem is coming from the base-uri

when I use
``base-uri: "https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a******"``
I get a null in the open id configuration url
``
2023-07-06T13:37:50.859+08:00 DEBUG 22676 --- [nio-8080-exec-2] o.s.web.client.RestTemplate              : HTTP GET https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a******/null/v2.0/.well-known/openid-configuration
``

and when I use  
``base-uri: "https://74aeca07-39b9-4721-8b96-428a******.b2clogin.com" ``

My JWT token is invalid because my azure ad b2c has a custom domain.
``
2023-07-06T13:31:37.382+08:00 DEBUG 26104 --- [nio-8080-exec-1] o.s.s.o.s.r.a.JwtAuthenticationProvider  : Failed to authenticate since the JWT was invalid
``
Inside my jwt (issued from my frontend), the azure ad b2c set the following issuer
``
  "iss": "https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a******/v2.0/",
``


So maybe the problem come from the use of a custom domain in azure ad b2c ? 
is it possible to fill this 'null' part in the first configuration setup with any variable to set ?

Thanks a lot for your help


Actual configuration I just tried
````
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: "74aeca07-39b9-4721-8b96-428a********"
          app-id-uri: "41e8ee56-0d5b-4fed-a36e-ecf1189****"         # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          credential:
            client-id: "41e8ee56-0d5b-4fed-a36e-ecf1189****"           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: "https://ad.dev.datx.eu/74aeca07-39b9-4721-8b96-428a******"             # Such as: https://xxxxb2c.b2clogin.com
````
and

````
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: "74aeca07-39b9-4721-8b96-428a********"
          app-id-uri: "41e8ee56-0d5b-4fed-a36e-ecf1189****"         # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          credential:
            client-id: "41e8ee56-0d5b-4fed-a36e-ecf1189****"           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: "https://74aeca07-39b9-4721-8b96-428a******.b2clogin.com"             # Such as: https://xxxxb2c.b2clogin.com
````
