### ISSUE TITLE
[BUG] The retry options under the spring.cloud.azure.eventhubs.consumer are not applied correctly

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#35235]
**Describe the bug**
The retry functionality does not work, since the below configuration will not be applied correctly when using Spring Cloud Azure Stream Binder Event Hub.

```properties
spring.cloud.azure.eventhubs.consumer.retry.mode=exponential
spring.cloud.azure.eventhubs.consumer.retry.try-timeout=2
spring.cloud.azure.eventhubs.consumer.retry.exponential.base-delay=PT1S
spring.cloud.azure.eventhubs.consumer.retry.exponential.max-delay=PT3S
spring.cloud.azure.eventhubs.consumer.retry.exponential.max-retries=3
```

***Exception or Stack Trace***
N/A

**To Reproduce**
- Clone the [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder)
- Add the below consumer retry options

```yaml
spring:
  cloud:
    azure:
      eventhubs:
        consumer:
          retry:
            mode: exponential
            try-timeout: 2
            exponential:
              base-delay: PT1S
              max-delay: PT3S
              max-retries: 3
```
- Run the app, check the options on Event Hubs client

***Code Snippet***
N/A

**Expected behavior**
The retry options should only be taken for the consumer client, maybe all Azure SDK client, and the [documentation](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-all) should be synced as well.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-eventhubs:4.8.0
 - Java version: 17
 - Frameworks: Spring Boot 2.7.11

**Additional context**
The same issues may exist for client options and proxy options, as well as the Service Bus side.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by moarychan** [comment]
A workaround is to move the retry options to `spring.cloud.azure.eventhubs`, such as below configuration:
```yml
spring:
  cloud:
    azure:
      eventhubs:
        retry:
          mode: exponential
          try-timeout: PT2S
          exponential:
            base-delay: PT1S
            max-delay: PT3S
            max-retries: 3
```

**Comment by moarychan** [comment]
Service Bus also has this problem.

**Comment by vprudnikov** [comment]
Hi :)

Any input on this?

I tried to configure a retry policy for my application, and the following configuration doesn't get applied:
```
spring:
  cloud:
    azure:
      retry:
        exponential:
          max-retries: 3
          base-delay: PT1S
          max-delay: PT10S
        mode: exponential
      servicebus:
        namespace: ${AZURE_SERVICEBUS_NAMESPACE}
        retry:
          exponential:
            max-retries: 3
            base-delay: PT1S
            max-delay: PT10S
          mode: exponential
    stream:
      bindings:
        consumeDocumentChange-in-0:
          destination: documents
    function:
      definition: consumeDocumentChange;
```

The message is simply retried 10 times in a row.

Thank you!
