### ISSUE TITLE
[FEATURE REQ] ServiceBus: Improve maxConcurrentCalls documentation to prevent production incidents

### ISSUE THREAD

**Issue by gbrehmer** [Azure/azure-sdk-for-java#37192]
https://github.com/Azure/azure-sdk-for-java/blob/8b6f7e4b7bde29f5d0a81eb2415beddc9b682db6/sdk/servicebus/azure-messaging-servicebus/TROUBLESHOOTING.md?plain=1#L26
This important notice should be added to the configuration documentation of max-concurrent-calls and prefetch-count, e.g.: 

https://github.com/Azure/azure-docs-sdk-java/blob/cef4e0be8839c16a71f3d5dc57fd96c7dcbbc41d/docs-ref-autogen/com.azure.messaging.servicebus.ServiceBusClientBuilder.ServiceBusProcessorClientBuilder.yml#L59

If you searching for this exception/behavior its already too late and this parameter has produced an incident in the production environment. We had an incident because we have defined several consumers with prefetch and maxConcurrentCalls, but in our stage system this error does not occur, because we have not all consumers in use there (queues from different azure regions). And it was working before in another production system with more host resources (but this was shared environment, we moved now to AKS and have dedicated but more limited ressources (4 vs 1 CPU)

**Comment by anuchandy** [comment]
Hello @gbrehmer, thanks for reaching out! We’ll improve the Java-Doc here. Just curious, could you let me know the following - 
1.	In AKS you mentioned each Pod has 1 core. How many ProcessorClient instances are you running on one such Pod?
2.	What is the Prefetch and MaxConcurrentCalls set for an instance of ProcessorClient?

**Comment by gbrehmer** [comment]
Sure I forgot that there are several possibilities to achieve the same result:
We are currently not using the programmatic approach. We are using spring-cloud-stream servicebus and for this mainly spring yaml configuration. Because of that javadoc would not automatically help in cases like ours I think, because we made the configuration e.g. on basis of this documentation page: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-stream-support?tabs=SpringCloudAzure4x

would you rather recommend a programmatic approach for the configuration?

our use case:
we have in production 4 consumer with in total 16 "concurrent calls". The pod has only one container (spring boot service) with cpu limit `1000m`

```
  cloud:
    stream:
      servicebus:
        bindings:
          serviceBusQueueWestEurope-in-0:
            consumer:
              auto-complete: false
              max-concurrent-calls: 6
              prefetch-count: 5
          serviceBusQueueEastAsia-in-0:
            consumer:
              auto-complete: false
          serviceBusQueueCentralUs-in-0:
            consumer:
              auto-complete: false
              max-concurrent-calls: 6
              prefetch-count: 5
          serviceBusQueueAustraliaEast-in-0:
            consumer:
              auto-complete: false
              max-concurrent-calls: 3
```
