### ISSUE TITLE
[Stop consuming messages by using spring-cloud-azure-stream-binder-servicebus 5.3.0 with auto ack or manual ack]

### ISSUE THREAD

**Issue by XiaoYue2-22** [Azure/azure-sdk-for-java#37982]
**Describe the bug**
application running in AKS will stop consuming messages when we tried to consume more than 6000 messages using auto ack.
It also happens intermittently when using manual ack.

***Exception or Stack Trace***

```console

{"az.sdk.message":"Acquired   a new access token."} 

{"az.sdk.message":"Acquired   a new access token."} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_dd6cc3_1701761674700"}   
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"}|  
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"onTransportError","connectionId":"MF_655949_1701761662572","errorCondition":"amqp:connection:framing-error","errorCondition":"connection   aborted","hostName":"demonamespace.servicebus.windows.net"}
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"}
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"}
{"az.sdk.message":"Retry   attempts exhausted or exception was not   retriable.","exception":"Unable to open send and receive   link.","connectionId":"MF_655949_1701761662572","entityPath":"$cbs","tryCount":0}
{"az.sdk.message":"signalWorkQueue   failed before reactor   closed.","exception":null,"connectionId":"MF_655949_1701761662572"}
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 
{"az.sdk.message":"Unable   to open send and receive link.","exception":"Unable to   open send and receive   link.","connectionId":"MF_655949_1701761662572","linkName":"cbs"} 
{"az.sdk.message":"ReactorDispatcher   instance is closed. Should not continue dispatching work to this   reactor.","exception":"ReactorDispatcher instance is   closed. Should not continue dispatching work to this reactor.","connectionId":"MF_655949_1701761662572"} 

```

**To Reproduce**
1. in our production environment, there are many messages sent to service bus and also multiple applications listen to different topics, we observed several threads related to one topic will be unable to consumer messages on time and then stopped consuming messages. 
Issue will not happen when messages are consumed timely. We don't see any CPU, memory issue in platform or server side.
3. Hence, we did below test trying to simulate the same scenario in production:
2.1. sent messages to service bus but not consume them.
2.2 stopped send message and start to consume message, total message is 6107 messages, but the application stopped consuming after around 1000 messages, still Remaining 4676 message are unable to be consumed.
Message size: around 1KB
**spring-cloud-azure-stream-binder-servicebus 5.3.0**

```yaml
auto ack configuration:
       default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    namespace: demonamespace
                  resource:
                    resourceGroup: demoresourceGroup
                  entityType: topic
                  entityName: demoentityname
                  profile:
                    tenant-id: 111111111111111111111111111111
                  credential:
                    fullyQualifiedNamespace: demonamespace.servicebus.windows.net
                    client-id: 111111111111111111111111111
                    client-secret: 111111111111111111111
      bindings:
        autoACKConsume-in-0:
          destination: demoentityname
          group: demoentitynamesubscription
          binder: demo-asbbinder
      servicebus:
        bindings:
          autoACKConsume-in-0:
            consumer:
              autoComplete: true
              session-enabled: true
              maxConcurrentSessions: 50
```
***Code Snippet***
```java
package demo.consumer;

import com.azure.spring.messaging.AzureHeaders;
import com.azure.spring.messaging.checkpoint.Checkpointer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.messaging.Message;

import java.util.Map;
import java.util.function.Consumer;

@Configuration
public class DemoASBConsumer {

    @Bean
    public Consumer<Message<String>> autoACKConsume(Map<String, String> handlerMap) {
        return message -> {
            //consumer logic
        };
    }

    @Bean
    public Consumer<Message<String>> manualACKConsume(Map<String, String> handlerMap) {
        return message -> {
            Checkpointer checkpointer = message.getHeaders().get(AzureHeaders.CHECKPOINTER, Checkpointer.class);
            checkpointer.success()
                    .doOnSuccess(s -> {
                        //consumer logic
                    })
                    .doOnError(error -> log.error("manualACKConsume Exception", error))
                    .block();
        };
    }
}
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
- IDE: [e.g. IntelliJ]
- Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
- Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
- Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added
