### ISSUE TITLE
[BUG] More than 1 Connection method was set for connecting to App Configuration

### ISSUE THREAD

**Issue by diegopatinor** [Azure/azure-sdk-for-java#38732]
We have updated the Spring Boot version to `3.1.5`, which also meant updating spring-cloud-azure-dependencies to `5.9.1`.

We have an integration with Azure App Configuration, with the following configuration.

```
spring.cloud.azure.appconfiguration.stores:
  - connection-string: Endpoint=https://<app-config>.azconfig.azure.us;Id=<Id>;Secret=<Secret>
    feature-flags.enabled: true
    monitoring.feature-flag-refresh-interval: 30s
```

It is the same configuration that we had with `4.14.0`, which works without problems, now we get the following error.

```
{"timestamp":"2024-02-09T17:17:34.779Z","level":"ERROR","stack":"java.lang.IllegalArgumentException: More than 1 Connection method was set for connecting to App Configuration.
	 com.azure.spring.cloud.appconfigurion.config.implemention.AppConfigurionReplicaClientsBuilder.buildClients(AppConfigurionReplicaClientsBuilder.java:143)
	 com.azure.spring.cloud.appconfigurion.config.implemention.ConnectionManager.getAvailableClients(ConnectionManager.java:84)
	 com.azure.spring.cloud.appconfigurion.config.implemention.AppConfigurionReplicaClientFactory.getAvailableClients(AppConfigurionReplicaClientFactory.java:60)
	 com.azure.spring.cloud.appconfigurion.config.implemention.AppConfigurionPropertySourceLocor.loce(AppConfigurionPropertySourceLocor.java:108)
	 org.springframework.cloud.bootstrap.config.PropertySourceLocor.loceCollection(PropertySourceLocor.java:50)
	 org.springframework.cloud.bootstrap.config.PropertySourceLocor.loceCollection(PropertySourceLocor.java:46)
	 org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfigurion.doInitialize(PropertySourceBootstrapConfigurion.java:121)
	 org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfigurion.initialize(PropertySourceBootstrapConfigurion.java:111)
	 org.springframework.boot.SpringApplicion.applyInitializers(SpringApplicion.java:611)
	 org.springframework.boot.SpringApplicion.prepareContext(SpringApplicion.java:391)
	 org.springframework.boot.SpringApplicion.run(SpringApplicion.java:315)
	 org.springframework.boot.SpringApplicion.run(SpringApplicion.java:1306)
	 org.springframework.boot.SpringApplicion.run(SpringApplicion.java:1295)
	 com.safefleet.tenant.security.api.TenantSecurityApiApplicion.main(TenantSecurityApiApplicion.java:21)
	 java.base/jdk.internal.reflect.NiveMethodAccessorImpl.invoke0(Nive Method)
	 java.base/jdk.internal.reflect.NiveMethodAccessorImpl.invoke(Unknown Source)
	 java.base/jdk.internal.reflect.DelegingMethodAccessorImpl.invoke(Unknown Source)
	 java.base/java.lang.reflect.Method.invoke(Unknown Source)
	 org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	 org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	 org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	 org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
","message":"Applicion run failed"}
```
Something important to mention is that local works without any problem, we get the error in our Azure Kubernetes Service.

Is there something we are missing in the update process?

**Version Summary**
Java: 17
Spring Boot 3.1.5
Spring Cloud: 2022.0.4
Spring Cloud Azure Dependencies: 5.9.1
Azure: Government

**Comment by mrm9084** [comment]
@diegopatinor there shouldn't be any difference between the 4.x and 5.x versions. I'm looking into it.

Just to verify, you are using the connection-string for both local and AKS?

Also, have you setup replica usage with the `connection-strings` or `endpoints` options?

**Comment by diegopatinor** [comment]
@mrm9084 Hi, thanks for answering

I have found the problem, with this new update, we also added new functionality with EventHubs, before we only had integration with a queue and the appconfiguration, and in our configuration, the credentials were changed to the root, so as not to have to replicate them for each service. In the following way

```
...
    azure:
      profile:
        tenant-id: <tenant-id>
        cloud-type: AZURE_US_GOVERNMENT
      credential:
        client-id: <client-id>
        client-secret: <client-secret>
      storage:
        queue:
          account-name: <account-name>
          queue-name: <queue-name>
      eventhubs:
        connection-string: <connection-string>
        namespace: <namespace>
        processor:
          checkpoint-store:
            account-name: <account-name>
            container-name: <account-name>
```

So, to use the String Connection for app configuration, we had to change it as follows.

```
    azure:
      profile:
        tenant-id: <tenant-id>
        cloud-type: AZURE_US_GOVERNMENT
      storage:
        queue:
          credential:
            client-id: <client-id>
            client-secret: <client-secret>
          account-name: <account-name>
          queue-name: <queue-name>
      eventhubs:
        connection-string: < connection-string>
        namespace: <namespace>
        processor:
          checkpoint-store:
            credential:
              client-id: <client-id>
              client-secret: <client-secret>
            account-name: <account-name>
            container-name: <container-name>
```

That is, remove the general credentials and add them to each service.

It made us doubt that local configurations work without any problem with the first one.
