### ISSUE TITLE
[BUG] Feature Management no longer working in 5.14.0

### ISSUE THREAD

**Issue by alex-kuck** [Azure/azure-sdk-for-java#41175]
**Describe the bug**
After updating `com.azure.spring:spring-cloud-azure-appconfiguration-config-web` and `com.azure.spring:spring-cloud-azure-feature-management-web` from `5.13.0` to `5.14.0` the feature management using the Azure App Configuration is no longer working, i.e. always returning `false` for all features.

***Exception or Stack Trace***
N/A

**To Reproduce**
Update existing Spring Boot app to use `5.14.0` of Azure libraries

***Code Snippet***
N/A

**Expected behavior**
A minor version bump should work as before without requiring any configuration changes or similar.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Linux/Docker
 - IDE: IntelliJ
 - Library/Libraries: 
        implementation("com.azure.spring:spring-cloud-azure-appconfiguration-config-web:5.14.0")
	implementation("com.azure.spring:spring-cloud-azure-feature-management-web:5.14.0")
 - Java version: 17 
 - Frameworks: Spring Boot 3.3.1

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

bootstrap.yaml (working with 5.13.0):
```yaml
spring.cloud.azure.appconfiguration:
  enabled: true
  stores:
    - connection-string: ${AZURE_APP_CONFIGURATION_CONNECTION_STRING:}
      monitoring:
        enabled: true
        triggers:
          - key: sentinel
        feature-flag-refresh-interval: 30s
      feature-flags:
        enabled: true
        selects:
          - label-filter: ',${AZURE_APP_CONFIGURATION_LABEL:}'
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added
