### ISSUE TITLE
[FEATURE REQ] Missing "additional-spring-configuration-metadata.json" in artifact spring-cloud-azure-starter-appconfiguration-config

### ISSUE THREAD

**Issue by 1goldenboy** [Azure/azure-sdk-for-java#41502]
**Is your feature request related to a problem? Please describe.**
Intellij issues warnings when using the configuration properties available in spring-cloud-azure-starter-appconfiguration-config. It seems that Intellij is unable to pick up AppConfigurationProperties.class in spring-cloud-azure-starter-appconfiguration-config. Instead it picks up AppConfigurationProperties.class in spring-cloud-azure-autoconfigure and marks the other properties as missing. For example considering this configuration in bootstrap.yaml
```
spring:
  cloud:
    azure:
      appconfiguration:
        enabled: true
        stores:
          - endpoint: 'https://my-store-in-azure.azconfig.io'
            feature-flags:
              enabled: true
            selects:
              - keyFilter: '/my-api/'
```
Then "enabled" would not be marked since it is present in both the classes, but "stores" would be marked as missing since its only present in  spring-cloud-azure-starter-appconfiguration-config

**Describe the solution you'd like**
I believe adding the following dependency to the classpath when compiled would solve the issue
```
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
</dependency>
```
However, investigating it seems that all properties is defined in spring-cloud-azure-autoconfigure, so perhaps it should be updated there instead?

**Describe alternatives you've considered**
Ignore the warnings 

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified
