### ISSUE TITLE
[QUERY] Is spring.cloud.azure.cosmos.content-response-on-write-enable a valid configurable property I have control over in Azure Spring Cosmos?

### ISSUE THREAD

**Issue by MapFilterMagic** [Azure/azure-sdk-for-java#42590]
**Query/Question**
Is `spring.cloud.azure.cosmos.content-response-on-write-enabled` a valid autoconfiguration property? Should setting it to `false` result in the `contentResponseOnWriteEnabled` config option being disabled? Because I haven't gotten it to work.

I've tried it through my yaml configs like:

```yaml
spring:
    cloud:
        azure:
            cosmos:
                endpoint: https://my-example-db-account.documents.azure.com:443
                key: my-secret-key
                database: my-db 
                populate-query-metrics: false
                client-telemetry-enabled: false
                content-response-on-write-enabled: false
```

<p>

And I've tried setting it while manually building up my client like what shows up in this example https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-data-cosmos/README.md#setup-configuration-class like this:

```java

    ...

    @Bean
    public CosmosClientBuilder getCosmosClientBuilder() {
        this.azureKeyCredential = new AzureKeyCredential(key);
        DirectConnectionConfig directConnectionConfig = new DirectConnectionConfig();
        GatewayConnectionConfig gatewayConnectionConfig = new GatewayConnectionConfig();

        return new CosmosClientBuilder()
            .preferredRegions(preferredRegions)
            .contentResponseOnWriteEnabled(false)
            .endpoint(uri)
            .credential(azureKeyCredential)
            .directMode(directConnectionConfig, gatewayConnectionConfig)
            .clientTelemetryConfig(
                new CosmosClientTelemetryConfig()
                    .metricsOptions(
                        new CosmosMicrometerMetricsOptions()
                        .setEnabled(false)
                    )
                    .diagnosticsHandler(CosmosDiagnosticsHandler.DEFAULT_LOGGING_HANDLER));
    }

    ...
```

<br>

But neither seem to flip this option off according to the application output on startup once it builds the client:
![Image](https://github.com/user-attachments/assets/d4575478-dda5-4ffd-a2a9-5a51a7da4896)

<br>

Disabling this option shows up in the recommended SDK best practices for performance, and it's listed as a valid configuration here: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-cosmos-db

Any ideas?

***Why is this not a Bug or a feature Request?***
I'm trying to gather more information on if I'm doing something wrong or if this is just expected behavior.

**Setup (please complete the following information if applicable):**
 - OS: macOS,  jdk21 (oracle open jdk 21.0.5)
 - Library/Libraries:
   - `org.springframework.boot:spring-boot-starter-parent:3.3.3`
   - `com.azure.spring:spring-cloud-azure-dependencies:5.17.1`
   - `org.springframework.cloud:spring-cloud-dependencies:2023.0.3`
   - `com.azure.spring:spring-cloud-azure-starter-data-cosmos`
   - `com.azure.spring:spring-cloud-azure-starter-actuator`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added
