### ISSUE TITLE
[BUG] Service bus custom endpoint address

### ISSUE THREAD

**Issue by Anton0123** [Azure/azure-sdk-for-java#43555]
**Describe the bug**
The custom endpoint address is not merged from the namespace properties to producer/processor/consumer properties. This results in the custom endpoint address being null.

**To Reproduce**
Configure a custom endpoint address for the namespace but not for individual consumers or producers. The custom endpoint address will not be used when sending or receiving messages.

***Code Snippet***
Example configuration
``` YAML
spring:
  cloud:
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: sbq-test-1
        supply-out-0:
          destination: sbq-test-2
      binders:
        servicebus-0:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  client:
                    amqp:
                      transport-type: amqp_web_sockets
                  servicebus:
                    custom-endpoint-address: https://test.address.com:443
                    namespace: sb-test-1
                    credential:
                      client-id: ${CLIENT_ID}
                      client-secret: ${CLIENT_SECRET}
                    profile:
                      tenant-id: ${TENANT_ID}
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              entity-type: queue
          supply-out-0:
            producer:
              entity-type: queue
```

**Expected behavior**
I expect the custom-endpoint-address to be used by the consumers/producers/processors.

**Screenshots**
![Image](https://github.com/user-attachments/assets/100bdc89-4cea-44b9-a5f2-01835a5a34a3)

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-servicebus:5.19.0
 - Java version: 22
 - App Server/Environment:  -
 - Frameworks: Spring boot

**Additional context**
See `com.azure.spring.messaging.servicebus.implementation.properties.merger`, for example `SenderPropertiesParentMerger`. It does not map the custom endpoint address.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-messaging-azure-servicebus/src/main/java/com/azure/spring/messaging/servicebus/implementation/properties/merger/SenderPropertiesParentMerger.java
