### ISSUE TITLE
[BUG] Possible regression `WorkloadIdentityCredential` for `spring-cloud-azure>=5.18.0`

### ISSUE THREAD

**Issue by thepaulroman** [Azure/azure-sdk-for-java#43787]
**Describe the bug**

Similar to #42979, but instead, it is in the context of using `WorkloadIdentityCredential` as our app is deployed on AKS.

Last working version on AKS:
 
| Dep | Version |
| ---- | -------| 
| `spring-cloud-azure` | `5.17.1` |
| `spring-cloud` | `2023.0.5` |
| `spring-boot` | `3.3.7` |

As a part of our regular dependency updates as we want to keep close to latest, we've observed the below problem with WorkloadIdentity.

***Exception or Stack Trace***
```
Caused by: com.microsoft.aad.msal4j.MsalAzureSDKException: java.util.concurrent.ExecutionException: com.azure.identity.CredentialUnavailableException: WorkloadIdentityCredential authentication unavailable. The request to the authority host was invalid. Additional details: Server returned HTTP response code: 400 for URL: https://login.chinacloudapi.cn/redacted-client-id-of-user-assigned-identity/oauth2/v2.0/token.
```

**To Reproduce**

Keyvault starter as a dependency, spring boot is configured to use the keyvault with property source.


```yaml
  # Azure configurations
  cloud:
    azure:
      credential:
        client-id: ${identity-id}
        managed-identity-enabled: true
      profile:
        cloud-type: azure_china
        tenant-id: ${tenant-id}
        subscription-id: ${subscription-id}

      # Keyvault configurations
      keyvault:
        secret:
          property-sources:
            - name: keyvault
              endpoint: ${KEYVAULT_ENDPOINT:https://redacted-against-doxxing.vault.azure.cn/}
          property-source-enabled: true
```

***Code Snippet***

Using latest GA versions as of now triggers the exception:

| Dep | Version |
| ---- | -------| 
| `spring-cloud-azure` | `5.19.0` |
| `spring-cloud` | `2024.0.0` |
| `spring-boot` | `3.4.1` |

**Expected behavior**
Keyvault is able to use `WorkloadIdentityCredential` as in version `<5.18.0` to pull the required secrets for our application.

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries:`com.azure.spring:spring-cloud-azure-starter-keyvault:5.19.0`
 - Java version: 21 
 - App Server/Environment: AKS
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

The service account is deployed and successfuly sets the following environment variables on the pod, as usual:
```yaml
AZURE_CLIENT_ID:                                    never-gonna-give-you-up                                                                                                                                                                                                                              
AZURE_TENANT_ID:                                    never-gonna-let-you-down                                                                                                                                                                                                                              
AZURE_FEDERATED_TOKEN_FILE:                         /var/run/secrets/azure/tokens/azure-identity-token                                                                                                                                                                                                                
AZURE_AUTHORITY_HOST:                               https://login.chinacloudapi.cn/
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@moarychan @billwert could you please take a look at the setup

**Comment by moarychan** [comment]
Hi @thepaulroman , thanks for using Spring Cloud Azure！

There's a similar issue https://github.com/Azure/azure-sdk-for-java/issues/42979 due the same root cause, the property `spring.cloud.azure.credential.managed-identity-enabled=true` is not taken properly, the `WorkloadIdentityCredential` will read the environment variables (`AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_FEDERATED_TOKEN_FILE, AZURE_AUTHORITY_HOST`) then it works; otherwise, you should use the `ManagedIdentityCredential`, please check this https://github.com/Azure/azure-sdk-for-java/issues/42979#issuecomment-2559274509. Please remove the property spring.cloud.azure.credential.managed-identity-enabled` configuration, then they behaviors should be same in the two versions.

**Comment by thepaulroman** [comment]
> Hi [@thepaulroman](https://github.com/thepaulroman) , thanks for using Spring Cloud Azure！
> 
> There's a similar issue [#42979](https://github.com/Azure/azure-sdk-for-java/issues/42979) due the same root cause, the property `spring.cloud.azure.credential.managed-identity-enabled=true` is not taken properly, the `WorkloadIdentityCredential` will read the environment variables (`AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_FEDERATED_TOKEN_FILE, AZURE_AUTHORITY_HOST`) then it works; otherwise, you should use the `ManagedIdentityCredential`, please check this [#42979 (comment)](https://github.com/Azure/azure-sdk-for-java/issues/42979#issuecomment-2559274509). Please remove the property spring.cloud.azure.credential.managed-identity-enabled` configuration, then they behaviors should be same in the two versions.

Thanks for this, @moarychan! Can confirm that using:

Dep | Version
-- | --
`spring-cloud-azure` | `5.19.0`
`spring-cloud` | `2024.0.0`
`spring-boot` | `3.4.1`

Having these environment variables:

```yaml
AZURE_CLIENT_ID:                                    never-gonna-give-you-up                                                                                                                                                                                                                              
AZURE_TENANT_ID:                                    never-gonna-let-you-down                                                                                                                                                                                                                              
AZURE_FEDERATED_TOKEN_FILE:                         /var/run/secrets/azure/tokens/azure-identity-token                                                                                                                                                                                                                
AZURE_AUTHORITY_HOST:                               https://login.chinacloudapi.cn/
```

And using this application.yaml configuration:

```yaml
  # Azure configurations
  cloud:
    azure:
      credential:
        client-id: ${identity-id}
        # managed-identity-enabled: true ref: https://github.com/Azure/azure-sdk-for-java/issues/43787#issuecomment-2597794271
      profile:
        cloud-type: azure_china
        tenant-id: ${tenant-id}
        subscription-id: ${subscription-id}

      # Keyvault configurations
      keyvault:
        secret:
          property-sources:
            - name: keyvault
              endpoint: ${KEYVAULT_ENDPOINT:https://redacted-against-doxxing.vault.azure.cn/}
          property-source-enabled: true
```
Produces the following result as seen in the log messages: 

```
Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID
Azure Identity => Managed Identity environment: AZURE AKS TOKEN EXCHANGE
```

Thanks for helping me get a solution to this. 

Was definitely confused by the setting name `managed-identity-enabled: true`, as logically speaking, it would be a no-brainer to have this enabled, going by the name. 

Maybe this content needs updating?
ref. https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/authentication.md

Thanks again for assisting me on this, have a nice weekend!
