### ISSUE TITLE
Cleanup: use the OS Variables from eng/pipelines/templates/variables/image.yml

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#44548]
Right now, we've got a lot of places in the pipeline yml files where we've hardcoded OS pools
```
pool:
     name: azsdk-pool-mms-win-2022-general
     image: azsdk-pool-mms-win-2022-1espt
     os: windows

```

We should be using the values from eng/pipelines/templates/variables/image.yml
