### ISSUE TITLE
Miss one storage error code "AuthenticationError"

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4980]
Storage queue returns StorageErrorException of "AuthenticationError" when we passed in the metadata with capital letter.

There is no such constant error code in swagger in java.

**Comment by sima-zhu** [comment]
@rickle-msft @tg-msft

**Comment by tg-msft** [comment]
You'll want to add this to https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-queue/swagger/README.md with a transform like:

```yaml
directive:
- from: swagger-document
  where: $.definitions.ErrorCode
  transform: >
    if (!$.includes("AuthenticationError")) {
        $.push("AuthenticationError");
    }
```

And then regenerate following the instructions at the top of that file.
